// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	kappctrl "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apis/kappctrl"
	versionsv1alpha1 "github.com/vmware-tanzu/carvel-vendir/pkg/vendir/versions/v1alpha1"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*App)(nil), (*kappctrl.App)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_App_To_kappctrl_App(a.(*App), b.(*kappctrl.App), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.App)(nil), (*App)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_App_To_v1alpha1_App(a.(*kappctrl.App), b.(*App), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppCluster)(nil), (*kappctrl.AppCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppCluster_To_kappctrl_AppCluster(a.(*AppCluster), b.(*kappctrl.AppCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppCluster)(nil), (*AppCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppCluster_To_v1alpha1_AppCluster(a.(*kappctrl.AppCluster), b.(*AppCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppClusterKubeconfigSecretRef)(nil), (*kappctrl.AppClusterKubeconfigSecretRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppClusterKubeconfigSecretRef_To_kappctrl_AppClusterKubeconfigSecretRef(a.(*AppClusterKubeconfigSecretRef), b.(*kappctrl.AppClusterKubeconfigSecretRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppClusterKubeconfigSecretRef)(nil), (*AppClusterKubeconfigSecretRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppClusterKubeconfigSecretRef_To_v1alpha1_AppClusterKubeconfigSecretRef(a.(*kappctrl.AppClusterKubeconfigSecretRef), b.(*AppClusterKubeconfigSecretRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppCondition)(nil), (*kappctrl.AppCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppCondition_To_kappctrl_AppCondition(a.(*AppCondition), b.(*kappctrl.AppCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppCondition)(nil), (*AppCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppCondition_To_v1alpha1_AppCondition(a.(*kappctrl.AppCondition), b.(*AppCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppDeploy)(nil), (*kappctrl.AppDeploy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppDeploy_To_kappctrl_AppDeploy(a.(*AppDeploy), b.(*kappctrl.AppDeploy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppDeploy)(nil), (*AppDeploy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppDeploy_To_v1alpha1_AppDeploy(a.(*kappctrl.AppDeploy), b.(*AppDeploy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppDeployKapp)(nil), (*kappctrl.AppDeployKapp)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppDeployKapp_To_kappctrl_AppDeployKapp(a.(*AppDeployKapp), b.(*kappctrl.AppDeployKapp), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppDeployKapp)(nil), (*AppDeployKapp)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppDeployKapp_To_v1alpha1_AppDeployKapp(a.(*kappctrl.AppDeployKapp), b.(*AppDeployKapp), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppDeployKappDelete)(nil), (*kappctrl.AppDeployKappDelete)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppDeployKappDelete_To_kappctrl_AppDeployKappDelete(a.(*AppDeployKappDelete), b.(*kappctrl.AppDeployKappDelete), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppDeployKappDelete)(nil), (*AppDeployKappDelete)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppDeployKappDelete_To_v1alpha1_AppDeployKappDelete(a.(*kappctrl.AppDeployKappDelete), b.(*AppDeployKappDelete), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppDeployKappInspect)(nil), (*kappctrl.AppDeployKappInspect)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppDeployKappInspect_To_kappctrl_AppDeployKappInspect(a.(*AppDeployKappInspect), b.(*kappctrl.AppDeployKappInspect), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppDeployKappInspect)(nil), (*AppDeployKappInspect)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppDeployKappInspect_To_v1alpha1_AppDeployKappInspect(a.(*kappctrl.AppDeployKappInspect), b.(*AppDeployKappInspect), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppFetch)(nil), (*kappctrl.AppFetch)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppFetch_To_kappctrl_AppFetch(a.(*AppFetch), b.(*kappctrl.AppFetch), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppFetch)(nil), (*AppFetch)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppFetch_To_v1alpha1_AppFetch(a.(*kappctrl.AppFetch), b.(*AppFetch), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppFetchGit)(nil), (*kappctrl.AppFetchGit)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppFetchGit_To_kappctrl_AppFetchGit(a.(*AppFetchGit), b.(*kappctrl.AppFetchGit), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppFetchGit)(nil), (*AppFetchGit)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppFetchGit_To_v1alpha1_AppFetchGit(a.(*kappctrl.AppFetchGit), b.(*AppFetchGit), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppFetchHTTP)(nil), (*kappctrl.AppFetchHTTP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppFetchHTTP_To_kappctrl_AppFetchHTTP(a.(*AppFetchHTTP), b.(*kappctrl.AppFetchHTTP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppFetchHTTP)(nil), (*AppFetchHTTP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppFetchHTTP_To_v1alpha1_AppFetchHTTP(a.(*kappctrl.AppFetchHTTP), b.(*AppFetchHTTP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppFetchHelmChart)(nil), (*kappctrl.AppFetchHelmChart)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppFetchHelmChart_To_kappctrl_AppFetchHelmChart(a.(*AppFetchHelmChart), b.(*kappctrl.AppFetchHelmChart), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppFetchHelmChart)(nil), (*AppFetchHelmChart)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppFetchHelmChart_To_v1alpha1_AppFetchHelmChart(a.(*kappctrl.AppFetchHelmChart), b.(*AppFetchHelmChart), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppFetchHelmChartRepo)(nil), (*kappctrl.AppFetchHelmChartRepo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppFetchHelmChartRepo_To_kappctrl_AppFetchHelmChartRepo(a.(*AppFetchHelmChartRepo), b.(*kappctrl.AppFetchHelmChartRepo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppFetchHelmChartRepo)(nil), (*AppFetchHelmChartRepo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppFetchHelmChartRepo_To_v1alpha1_AppFetchHelmChartRepo(a.(*kappctrl.AppFetchHelmChartRepo), b.(*AppFetchHelmChartRepo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppFetchImage)(nil), (*kappctrl.AppFetchImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppFetchImage_To_kappctrl_AppFetchImage(a.(*AppFetchImage), b.(*kappctrl.AppFetchImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppFetchImage)(nil), (*AppFetchImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppFetchImage_To_v1alpha1_AppFetchImage(a.(*kappctrl.AppFetchImage), b.(*AppFetchImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppFetchInline)(nil), (*kappctrl.AppFetchInline)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppFetchInline_To_kappctrl_AppFetchInline(a.(*AppFetchInline), b.(*kappctrl.AppFetchInline), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppFetchInline)(nil), (*AppFetchInline)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppFetchInline_To_v1alpha1_AppFetchInline(a.(*kappctrl.AppFetchInline), b.(*AppFetchInline), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppFetchInlineSource)(nil), (*kappctrl.AppFetchInlineSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppFetchInlineSource_To_kappctrl_AppFetchInlineSource(a.(*AppFetchInlineSource), b.(*kappctrl.AppFetchInlineSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppFetchInlineSource)(nil), (*AppFetchInlineSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppFetchInlineSource_To_v1alpha1_AppFetchInlineSource(a.(*kappctrl.AppFetchInlineSource), b.(*AppFetchInlineSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppFetchInlineSourceRef)(nil), (*kappctrl.AppFetchInlineSourceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppFetchInlineSourceRef_To_kappctrl_AppFetchInlineSourceRef(a.(*AppFetchInlineSourceRef), b.(*kappctrl.AppFetchInlineSourceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppFetchInlineSourceRef)(nil), (*AppFetchInlineSourceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppFetchInlineSourceRef_To_v1alpha1_AppFetchInlineSourceRef(a.(*kappctrl.AppFetchInlineSourceRef), b.(*AppFetchInlineSourceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppFetchLocalRef)(nil), (*kappctrl.AppFetchLocalRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppFetchLocalRef_To_kappctrl_AppFetchLocalRef(a.(*AppFetchLocalRef), b.(*kappctrl.AppFetchLocalRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppFetchLocalRef)(nil), (*AppFetchLocalRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppFetchLocalRef_To_v1alpha1_AppFetchLocalRef(a.(*kappctrl.AppFetchLocalRef), b.(*AppFetchLocalRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppList)(nil), (*kappctrl.AppList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppList_To_kappctrl_AppList(a.(*AppList), b.(*kappctrl.AppList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppList)(nil), (*AppList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppList_To_v1alpha1_AppList(a.(*kappctrl.AppList), b.(*AppList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppSpec)(nil), (*kappctrl.AppSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppSpec_To_kappctrl_AppSpec(a.(*AppSpec), b.(*kappctrl.AppSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppSpec)(nil), (*AppSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppSpec_To_v1alpha1_AppSpec(a.(*kappctrl.AppSpec), b.(*AppSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppStatus)(nil), (*kappctrl.AppStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppStatus_To_kappctrl_AppStatus(a.(*AppStatus), b.(*kappctrl.AppStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppStatus)(nil), (*AppStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppStatus_To_v1alpha1_AppStatus(a.(*kappctrl.AppStatus), b.(*AppStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppStatusDeploy)(nil), (*kappctrl.AppStatusDeploy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppStatusDeploy_To_kappctrl_AppStatusDeploy(a.(*AppStatusDeploy), b.(*kappctrl.AppStatusDeploy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppStatusDeploy)(nil), (*AppStatusDeploy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppStatusDeploy_To_v1alpha1_AppStatusDeploy(a.(*kappctrl.AppStatusDeploy), b.(*AppStatusDeploy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppStatusFetch)(nil), (*kappctrl.AppStatusFetch)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppStatusFetch_To_kappctrl_AppStatusFetch(a.(*AppStatusFetch), b.(*kappctrl.AppStatusFetch), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppStatusFetch)(nil), (*AppStatusFetch)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppStatusFetch_To_v1alpha1_AppStatusFetch(a.(*kappctrl.AppStatusFetch), b.(*AppStatusFetch), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppStatusInspect)(nil), (*kappctrl.AppStatusInspect)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppStatusInspect_To_kappctrl_AppStatusInspect(a.(*AppStatusInspect), b.(*kappctrl.AppStatusInspect), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppStatusInspect)(nil), (*AppStatusInspect)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppStatusInspect_To_v1alpha1_AppStatusInspect(a.(*kappctrl.AppStatusInspect), b.(*AppStatusInspect), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppStatusTemplate)(nil), (*kappctrl.AppStatusTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppStatusTemplate_To_kappctrl_AppStatusTemplate(a.(*AppStatusTemplate), b.(*kappctrl.AppStatusTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppStatusTemplate)(nil), (*AppStatusTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppStatusTemplate_To_v1alpha1_AppStatusTemplate(a.(*kappctrl.AppStatusTemplate), b.(*AppStatusTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppTemplate)(nil), (*kappctrl.AppTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppTemplate_To_kappctrl_AppTemplate(a.(*AppTemplate), b.(*kappctrl.AppTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppTemplate)(nil), (*AppTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppTemplate_To_v1alpha1_AppTemplate(a.(*kappctrl.AppTemplate), b.(*AppTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppTemplateHelmTemplate)(nil), (*kappctrl.AppTemplateHelmTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppTemplateHelmTemplate_To_kappctrl_AppTemplateHelmTemplate(a.(*AppTemplateHelmTemplate), b.(*kappctrl.AppTemplateHelmTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppTemplateHelmTemplate)(nil), (*AppTemplateHelmTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppTemplateHelmTemplate_To_v1alpha1_AppTemplateHelmTemplate(a.(*kappctrl.AppTemplateHelmTemplate), b.(*AppTemplateHelmTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppTemplateHelmTemplateValuesSource)(nil), (*kappctrl.AppTemplateHelmTemplateValuesSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppTemplateHelmTemplateValuesSource_To_kappctrl_AppTemplateHelmTemplateValuesSource(a.(*AppTemplateHelmTemplateValuesSource), b.(*kappctrl.AppTemplateHelmTemplateValuesSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppTemplateHelmTemplateValuesSource)(nil), (*AppTemplateHelmTemplateValuesSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppTemplateHelmTemplateValuesSource_To_v1alpha1_AppTemplateHelmTemplateValuesSource(a.(*kappctrl.AppTemplateHelmTemplateValuesSource), b.(*AppTemplateHelmTemplateValuesSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppTemplateHelmTemplateValuesSourceRef)(nil), (*kappctrl.AppTemplateHelmTemplateValuesSourceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppTemplateHelmTemplateValuesSourceRef_To_kappctrl_AppTemplateHelmTemplateValuesSourceRef(a.(*AppTemplateHelmTemplateValuesSourceRef), b.(*kappctrl.AppTemplateHelmTemplateValuesSourceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppTemplateHelmTemplateValuesSourceRef)(nil), (*AppTemplateHelmTemplateValuesSourceRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppTemplateHelmTemplateValuesSourceRef_To_v1alpha1_AppTemplateHelmTemplateValuesSourceRef(a.(*kappctrl.AppTemplateHelmTemplateValuesSourceRef), b.(*AppTemplateHelmTemplateValuesSourceRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppTemplateJsonnet)(nil), (*kappctrl.AppTemplateJsonnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppTemplateJsonnet_To_kappctrl_AppTemplateJsonnet(a.(*AppTemplateJsonnet), b.(*kappctrl.AppTemplateJsonnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppTemplateJsonnet)(nil), (*AppTemplateJsonnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppTemplateJsonnet_To_v1alpha1_AppTemplateJsonnet(a.(*kappctrl.AppTemplateJsonnet), b.(*AppTemplateJsonnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppTemplateKbld)(nil), (*kappctrl.AppTemplateKbld)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppTemplateKbld_To_kappctrl_AppTemplateKbld(a.(*AppTemplateKbld), b.(*kappctrl.AppTemplateKbld), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppTemplateKbld)(nil), (*AppTemplateKbld)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppTemplateKbld_To_v1alpha1_AppTemplateKbld(a.(*kappctrl.AppTemplateKbld), b.(*AppTemplateKbld), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppTemplateKustomize)(nil), (*kappctrl.AppTemplateKustomize)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppTemplateKustomize_To_kappctrl_AppTemplateKustomize(a.(*AppTemplateKustomize), b.(*kappctrl.AppTemplateKustomize), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppTemplateKustomize)(nil), (*AppTemplateKustomize)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppTemplateKustomize_To_v1alpha1_AppTemplateKustomize(a.(*kappctrl.AppTemplateKustomize), b.(*AppTemplateKustomize), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppTemplateSops)(nil), (*kappctrl.AppTemplateSops)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppTemplateSops_To_kappctrl_AppTemplateSops(a.(*AppTemplateSops), b.(*kappctrl.AppTemplateSops), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppTemplateSops)(nil), (*AppTemplateSops)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppTemplateSops_To_v1alpha1_AppTemplateSops(a.(*kappctrl.AppTemplateSops), b.(*AppTemplateSops), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppTemplateSopsPGP)(nil), (*kappctrl.AppTemplateSopsPGP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppTemplateSopsPGP_To_kappctrl_AppTemplateSopsPGP(a.(*AppTemplateSopsPGP), b.(*kappctrl.AppTemplateSopsPGP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppTemplateSopsPGP)(nil), (*AppTemplateSopsPGP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppTemplateSopsPGP_To_v1alpha1_AppTemplateSopsPGP(a.(*kappctrl.AppTemplateSopsPGP), b.(*AppTemplateSopsPGP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppTemplateSopsPGPPrivateKeysSecretRef)(nil), (*kappctrl.AppTemplateSopsPGPPrivateKeysSecretRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppTemplateSopsPGPPrivateKeysSecretRef_To_kappctrl_AppTemplateSopsPGPPrivateKeysSecretRef(a.(*AppTemplateSopsPGPPrivateKeysSecretRef), b.(*kappctrl.AppTemplateSopsPGPPrivateKeysSecretRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppTemplateSopsPGPPrivateKeysSecretRef)(nil), (*AppTemplateSopsPGPPrivateKeysSecretRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppTemplateSopsPGPPrivateKeysSecretRef_To_v1alpha1_AppTemplateSopsPGPPrivateKeysSecretRef(a.(*kappctrl.AppTemplateSopsPGPPrivateKeysSecretRef), b.(*AppTemplateSopsPGPPrivateKeysSecretRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AppTemplateYtt)(nil), (*kappctrl.AppTemplateYtt)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AppTemplateYtt_To_kappctrl_AppTemplateYtt(a.(*AppTemplateYtt), b.(*kappctrl.AppTemplateYtt), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.AppTemplateYtt)(nil), (*AppTemplateYtt)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_AppTemplateYtt_To_v1alpha1_AppTemplateYtt(a.(*kappctrl.AppTemplateYtt), b.(*AppTemplateYtt), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GenericStatus)(nil), (*kappctrl.GenericStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GenericStatus_To_kappctrl_GenericStatus(a.(*GenericStatus), b.(*kappctrl.GenericStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.GenericStatus)(nil), (*GenericStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_GenericStatus_To_v1alpha1_GenericStatus(a.(*kappctrl.GenericStatus), b.(*GenericStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstalledPkg)(nil), (*kappctrl.InstalledPkg)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstalledPkg_To_kappctrl_InstalledPkg(a.(*InstalledPkg), b.(*kappctrl.InstalledPkg), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.InstalledPkg)(nil), (*InstalledPkg)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_InstalledPkg_To_v1alpha1_InstalledPkg(a.(*kappctrl.InstalledPkg), b.(*InstalledPkg), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstalledPkgList)(nil), (*kappctrl.InstalledPkgList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstalledPkgList_To_kappctrl_InstalledPkgList(a.(*InstalledPkgList), b.(*kappctrl.InstalledPkgList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.InstalledPkgList)(nil), (*InstalledPkgList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_InstalledPkgList_To_v1alpha1_InstalledPkgList(a.(*kappctrl.InstalledPkgList), b.(*InstalledPkgList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstalledPkgPkgRef)(nil), (*kappctrl.InstalledPkgPkgRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstalledPkgPkgRef_To_kappctrl_InstalledPkgPkgRef(a.(*InstalledPkgPkgRef), b.(*kappctrl.InstalledPkgPkgRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.InstalledPkgPkgRef)(nil), (*InstalledPkgPkgRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_InstalledPkgPkgRef_To_v1alpha1_InstalledPkgPkgRef(a.(*kappctrl.InstalledPkgPkgRef), b.(*InstalledPkgPkgRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstalledPkgSpec)(nil), (*kappctrl.InstalledPkgSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstalledPkgSpec_To_kappctrl_InstalledPkgSpec(a.(*InstalledPkgSpec), b.(*kappctrl.InstalledPkgSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.InstalledPkgSpec)(nil), (*InstalledPkgSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_InstalledPkgSpec_To_v1alpha1_InstalledPkgSpec(a.(*kappctrl.InstalledPkgSpec), b.(*InstalledPkgSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstalledPkgStatus)(nil), (*kappctrl.InstalledPkgStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstalledPkgStatus_To_kappctrl_InstalledPkgStatus(a.(*InstalledPkgStatus), b.(*kappctrl.InstalledPkgStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.InstalledPkgStatus)(nil), (*InstalledPkgStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_InstalledPkgStatus_To_v1alpha1_InstalledPkgStatus(a.(*kappctrl.InstalledPkgStatus), b.(*InstalledPkgStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstalledPkgValues)(nil), (*kappctrl.InstalledPkgValues)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstalledPkgValues_To_kappctrl_InstalledPkgValues(a.(*InstalledPkgValues), b.(*kappctrl.InstalledPkgValues), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.InstalledPkgValues)(nil), (*InstalledPkgValues)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_InstalledPkgValues_To_v1alpha1_InstalledPkgValues(a.(*kappctrl.InstalledPkgValues), b.(*InstalledPkgValues), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstalledPkgValuesSecretRef)(nil), (*kappctrl.InstalledPkgValuesSecretRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstalledPkgValuesSecretRef_To_kappctrl_InstalledPkgValuesSecretRef(a.(*InstalledPkgValuesSecretRef), b.(*kappctrl.InstalledPkgValuesSecretRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.InstalledPkgValuesSecretRef)(nil), (*InstalledPkgValuesSecretRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_InstalledPkgValuesSecretRef_To_v1alpha1_InstalledPkgValuesSecretRef(a.(*kappctrl.InstalledPkgValuesSecretRef), b.(*InstalledPkgValuesSecretRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PkgRepository)(nil), (*kappctrl.PkgRepository)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PkgRepository_To_kappctrl_PkgRepository(a.(*PkgRepository), b.(*kappctrl.PkgRepository), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.PkgRepository)(nil), (*PkgRepository)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_PkgRepository_To_v1alpha1_PkgRepository(a.(*kappctrl.PkgRepository), b.(*PkgRepository), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PkgRepositoryFetch)(nil), (*kappctrl.PkgRepositoryFetch)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PkgRepositoryFetch_To_kappctrl_PkgRepositoryFetch(a.(*PkgRepositoryFetch), b.(*kappctrl.PkgRepositoryFetch), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.PkgRepositoryFetch)(nil), (*PkgRepositoryFetch)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_PkgRepositoryFetch_To_v1alpha1_PkgRepositoryFetch(a.(*kappctrl.PkgRepositoryFetch), b.(*PkgRepositoryFetch), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PkgRepositoryList)(nil), (*kappctrl.PkgRepositoryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PkgRepositoryList_To_kappctrl_PkgRepositoryList(a.(*PkgRepositoryList), b.(*kappctrl.PkgRepositoryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.PkgRepositoryList)(nil), (*PkgRepositoryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_PkgRepositoryList_To_v1alpha1_PkgRepositoryList(a.(*kappctrl.PkgRepositoryList), b.(*PkgRepositoryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PkgRepositorySpec)(nil), (*kappctrl.PkgRepositorySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PkgRepositorySpec_To_kappctrl_PkgRepositorySpec(a.(*PkgRepositorySpec), b.(*kappctrl.PkgRepositorySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.PkgRepositorySpec)(nil), (*PkgRepositorySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_PkgRepositorySpec_To_v1alpha1_PkgRepositorySpec(a.(*kappctrl.PkgRepositorySpec), b.(*PkgRepositorySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PkgRepositoryStatus)(nil), (*kappctrl.PkgRepositoryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PkgRepositoryStatus_To_kappctrl_PkgRepositoryStatus(a.(*PkgRepositoryStatus), b.(*kappctrl.PkgRepositoryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kappctrl.PkgRepositoryStatus)(nil), (*PkgRepositoryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kappctrl_PkgRepositoryStatus_To_v1alpha1_PkgRepositoryStatus(a.(*kappctrl.PkgRepositoryStatus), b.(*PkgRepositoryStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_App_To_kappctrl_App(in *App, out *kappctrl.App, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_AppSpec_To_kappctrl_AppSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_AppStatus_To_kappctrl_AppStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_App_To_kappctrl_App is an autogenerated conversion function.
func Convert_v1alpha1_App_To_kappctrl_App(in *App, out *kappctrl.App, s conversion.Scope) error {
	return autoConvert_v1alpha1_App_To_kappctrl_App(in, out, s)
}

func autoConvert_kappctrl_App_To_v1alpha1_App(in *kappctrl.App, out *App, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_kappctrl_AppSpec_To_v1alpha1_AppSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_kappctrl_AppStatus_To_v1alpha1_AppStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_kappctrl_App_To_v1alpha1_App is an autogenerated conversion function.
func Convert_kappctrl_App_To_v1alpha1_App(in *kappctrl.App, out *App, s conversion.Scope) error {
	return autoConvert_kappctrl_App_To_v1alpha1_App(in, out, s)
}

func autoConvert_v1alpha1_AppCluster_To_kappctrl_AppCluster(in *AppCluster, out *kappctrl.AppCluster, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.KubeconfigSecretRef = (*kappctrl.AppClusterKubeconfigSecretRef)(unsafe.Pointer(in.KubeconfigSecretRef))
	return nil
}

// Convert_v1alpha1_AppCluster_To_kappctrl_AppCluster is an autogenerated conversion function.
func Convert_v1alpha1_AppCluster_To_kappctrl_AppCluster(in *AppCluster, out *kappctrl.AppCluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppCluster_To_kappctrl_AppCluster(in, out, s)
}

func autoConvert_kappctrl_AppCluster_To_v1alpha1_AppCluster(in *kappctrl.AppCluster, out *AppCluster, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.KubeconfigSecretRef = (*AppClusterKubeconfigSecretRef)(unsafe.Pointer(in.KubeconfigSecretRef))
	return nil
}

// Convert_kappctrl_AppCluster_To_v1alpha1_AppCluster is an autogenerated conversion function.
func Convert_kappctrl_AppCluster_To_v1alpha1_AppCluster(in *kappctrl.AppCluster, out *AppCluster, s conversion.Scope) error {
	return autoConvert_kappctrl_AppCluster_To_v1alpha1_AppCluster(in, out, s)
}

func autoConvert_v1alpha1_AppClusterKubeconfigSecretRef_To_kappctrl_AppClusterKubeconfigSecretRef(in *AppClusterKubeconfigSecretRef, out *kappctrl.AppClusterKubeconfigSecretRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1alpha1_AppClusterKubeconfigSecretRef_To_kappctrl_AppClusterKubeconfigSecretRef is an autogenerated conversion function.
func Convert_v1alpha1_AppClusterKubeconfigSecretRef_To_kappctrl_AppClusterKubeconfigSecretRef(in *AppClusterKubeconfigSecretRef, out *kappctrl.AppClusterKubeconfigSecretRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppClusterKubeconfigSecretRef_To_kappctrl_AppClusterKubeconfigSecretRef(in, out, s)
}

func autoConvert_kappctrl_AppClusterKubeconfigSecretRef_To_v1alpha1_AppClusterKubeconfigSecretRef(in *kappctrl.AppClusterKubeconfigSecretRef, out *AppClusterKubeconfigSecretRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_kappctrl_AppClusterKubeconfigSecretRef_To_v1alpha1_AppClusterKubeconfigSecretRef is an autogenerated conversion function.
func Convert_kappctrl_AppClusterKubeconfigSecretRef_To_v1alpha1_AppClusterKubeconfigSecretRef(in *kappctrl.AppClusterKubeconfigSecretRef, out *AppClusterKubeconfigSecretRef, s conversion.Scope) error {
	return autoConvert_kappctrl_AppClusterKubeconfigSecretRef_To_v1alpha1_AppClusterKubeconfigSecretRef(in, out, s)
}

func autoConvert_v1alpha1_AppCondition_To_kappctrl_AppCondition(in *AppCondition, out *kappctrl.AppCondition, s conversion.Scope) error {
	out.Type = kappctrl.AppConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_AppCondition_To_kappctrl_AppCondition is an autogenerated conversion function.
func Convert_v1alpha1_AppCondition_To_kappctrl_AppCondition(in *AppCondition, out *kappctrl.AppCondition, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppCondition_To_kappctrl_AppCondition(in, out, s)
}

func autoConvert_kappctrl_AppCondition_To_v1alpha1_AppCondition(in *kappctrl.AppCondition, out *AppCondition, s conversion.Scope) error {
	out.Type = AppConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_kappctrl_AppCondition_To_v1alpha1_AppCondition is an autogenerated conversion function.
func Convert_kappctrl_AppCondition_To_v1alpha1_AppCondition(in *kappctrl.AppCondition, out *AppCondition, s conversion.Scope) error {
	return autoConvert_kappctrl_AppCondition_To_v1alpha1_AppCondition(in, out, s)
}

func autoConvert_v1alpha1_AppDeploy_To_kappctrl_AppDeploy(in *AppDeploy, out *kappctrl.AppDeploy, s conversion.Scope) error {
	out.Kapp = (*kappctrl.AppDeployKapp)(unsafe.Pointer(in.Kapp))
	return nil
}

// Convert_v1alpha1_AppDeploy_To_kappctrl_AppDeploy is an autogenerated conversion function.
func Convert_v1alpha1_AppDeploy_To_kappctrl_AppDeploy(in *AppDeploy, out *kappctrl.AppDeploy, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppDeploy_To_kappctrl_AppDeploy(in, out, s)
}

func autoConvert_kappctrl_AppDeploy_To_v1alpha1_AppDeploy(in *kappctrl.AppDeploy, out *AppDeploy, s conversion.Scope) error {
	out.Kapp = (*AppDeployKapp)(unsafe.Pointer(in.Kapp))
	return nil
}

// Convert_kappctrl_AppDeploy_To_v1alpha1_AppDeploy is an autogenerated conversion function.
func Convert_kappctrl_AppDeploy_To_v1alpha1_AppDeploy(in *kappctrl.AppDeploy, out *AppDeploy, s conversion.Scope) error {
	return autoConvert_kappctrl_AppDeploy_To_v1alpha1_AppDeploy(in, out, s)
}

func autoConvert_v1alpha1_AppDeployKapp_To_kappctrl_AppDeployKapp(in *AppDeployKapp, out *kappctrl.AppDeployKapp, s conversion.Scope) error {
	out.IntoNs = in.IntoNs
	out.MapNs = *(*[]string)(unsafe.Pointer(&in.MapNs))
	out.RawOptions = *(*[]string)(unsafe.Pointer(&in.RawOptions))
	out.Inspect = (*kappctrl.AppDeployKappInspect)(unsafe.Pointer(in.Inspect))
	out.Delete = (*kappctrl.AppDeployKappDelete)(unsafe.Pointer(in.Delete))
	return nil
}

// Convert_v1alpha1_AppDeployKapp_To_kappctrl_AppDeployKapp is an autogenerated conversion function.
func Convert_v1alpha1_AppDeployKapp_To_kappctrl_AppDeployKapp(in *AppDeployKapp, out *kappctrl.AppDeployKapp, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppDeployKapp_To_kappctrl_AppDeployKapp(in, out, s)
}

func autoConvert_kappctrl_AppDeployKapp_To_v1alpha1_AppDeployKapp(in *kappctrl.AppDeployKapp, out *AppDeployKapp, s conversion.Scope) error {
	out.IntoNs = in.IntoNs
	out.MapNs = *(*[]string)(unsafe.Pointer(&in.MapNs))
	out.RawOptions = *(*[]string)(unsafe.Pointer(&in.RawOptions))
	out.Inspect = (*AppDeployKappInspect)(unsafe.Pointer(in.Inspect))
	out.Delete = (*AppDeployKappDelete)(unsafe.Pointer(in.Delete))
	return nil
}

// Convert_kappctrl_AppDeployKapp_To_v1alpha1_AppDeployKapp is an autogenerated conversion function.
func Convert_kappctrl_AppDeployKapp_To_v1alpha1_AppDeployKapp(in *kappctrl.AppDeployKapp, out *AppDeployKapp, s conversion.Scope) error {
	return autoConvert_kappctrl_AppDeployKapp_To_v1alpha1_AppDeployKapp(in, out, s)
}

func autoConvert_v1alpha1_AppDeployKappDelete_To_kappctrl_AppDeployKappDelete(in *AppDeployKappDelete, out *kappctrl.AppDeployKappDelete, s conversion.Scope) error {
	out.RawOptions = *(*[]string)(unsafe.Pointer(&in.RawOptions))
	return nil
}

// Convert_v1alpha1_AppDeployKappDelete_To_kappctrl_AppDeployKappDelete is an autogenerated conversion function.
func Convert_v1alpha1_AppDeployKappDelete_To_kappctrl_AppDeployKappDelete(in *AppDeployKappDelete, out *kappctrl.AppDeployKappDelete, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppDeployKappDelete_To_kappctrl_AppDeployKappDelete(in, out, s)
}

func autoConvert_kappctrl_AppDeployKappDelete_To_v1alpha1_AppDeployKappDelete(in *kappctrl.AppDeployKappDelete, out *AppDeployKappDelete, s conversion.Scope) error {
	out.RawOptions = *(*[]string)(unsafe.Pointer(&in.RawOptions))
	return nil
}

// Convert_kappctrl_AppDeployKappDelete_To_v1alpha1_AppDeployKappDelete is an autogenerated conversion function.
func Convert_kappctrl_AppDeployKappDelete_To_v1alpha1_AppDeployKappDelete(in *kappctrl.AppDeployKappDelete, out *AppDeployKappDelete, s conversion.Scope) error {
	return autoConvert_kappctrl_AppDeployKappDelete_To_v1alpha1_AppDeployKappDelete(in, out, s)
}

func autoConvert_v1alpha1_AppDeployKappInspect_To_kappctrl_AppDeployKappInspect(in *AppDeployKappInspect, out *kappctrl.AppDeployKappInspect, s conversion.Scope) error {
	out.RawOptions = *(*[]string)(unsafe.Pointer(&in.RawOptions))
	return nil
}

// Convert_v1alpha1_AppDeployKappInspect_To_kappctrl_AppDeployKappInspect is an autogenerated conversion function.
func Convert_v1alpha1_AppDeployKappInspect_To_kappctrl_AppDeployKappInspect(in *AppDeployKappInspect, out *kappctrl.AppDeployKappInspect, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppDeployKappInspect_To_kappctrl_AppDeployKappInspect(in, out, s)
}

func autoConvert_kappctrl_AppDeployKappInspect_To_v1alpha1_AppDeployKappInspect(in *kappctrl.AppDeployKappInspect, out *AppDeployKappInspect, s conversion.Scope) error {
	out.RawOptions = *(*[]string)(unsafe.Pointer(&in.RawOptions))
	return nil
}

// Convert_kappctrl_AppDeployKappInspect_To_v1alpha1_AppDeployKappInspect is an autogenerated conversion function.
func Convert_kappctrl_AppDeployKappInspect_To_v1alpha1_AppDeployKappInspect(in *kappctrl.AppDeployKappInspect, out *AppDeployKappInspect, s conversion.Scope) error {
	return autoConvert_kappctrl_AppDeployKappInspect_To_v1alpha1_AppDeployKappInspect(in, out, s)
}

func autoConvert_v1alpha1_AppFetch_To_kappctrl_AppFetch(in *AppFetch, out *kappctrl.AppFetch, s conversion.Scope) error {
	out.Inline = (*kappctrl.AppFetchInline)(unsafe.Pointer(in.Inline))
	out.Image = (*kappctrl.AppFetchImage)(unsafe.Pointer(in.Image))
	out.HTTP = (*kappctrl.AppFetchHTTP)(unsafe.Pointer(in.HTTP))
	out.Git = (*kappctrl.AppFetchGit)(unsafe.Pointer(in.Git))
	out.HelmChart = (*kappctrl.AppFetchHelmChart)(unsafe.Pointer(in.HelmChart))
	return nil
}

// Convert_v1alpha1_AppFetch_To_kappctrl_AppFetch is an autogenerated conversion function.
func Convert_v1alpha1_AppFetch_To_kappctrl_AppFetch(in *AppFetch, out *kappctrl.AppFetch, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppFetch_To_kappctrl_AppFetch(in, out, s)
}

func autoConvert_kappctrl_AppFetch_To_v1alpha1_AppFetch(in *kappctrl.AppFetch, out *AppFetch, s conversion.Scope) error {
	out.Inline = (*AppFetchInline)(unsafe.Pointer(in.Inline))
	out.Image = (*AppFetchImage)(unsafe.Pointer(in.Image))
	out.HTTP = (*AppFetchHTTP)(unsafe.Pointer(in.HTTP))
	out.Git = (*AppFetchGit)(unsafe.Pointer(in.Git))
	out.HelmChart = (*AppFetchHelmChart)(unsafe.Pointer(in.HelmChart))
	return nil
}

// Convert_kappctrl_AppFetch_To_v1alpha1_AppFetch is an autogenerated conversion function.
func Convert_kappctrl_AppFetch_To_v1alpha1_AppFetch(in *kappctrl.AppFetch, out *AppFetch, s conversion.Scope) error {
	return autoConvert_kappctrl_AppFetch_To_v1alpha1_AppFetch(in, out, s)
}

func autoConvert_v1alpha1_AppFetchGit_To_kappctrl_AppFetchGit(in *AppFetchGit, out *kappctrl.AppFetchGit, s conversion.Scope) error {
	out.URL = in.URL
	out.Ref = in.Ref
	out.SecretRef = (*kappctrl.AppFetchLocalRef)(unsafe.Pointer(in.SecretRef))
	out.SubPath = in.SubPath
	out.LFSSkipSmudge = in.LFSSkipSmudge
	return nil
}

// Convert_v1alpha1_AppFetchGit_To_kappctrl_AppFetchGit is an autogenerated conversion function.
func Convert_v1alpha1_AppFetchGit_To_kappctrl_AppFetchGit(in *AppFetchGit, out *kappctrl.AppFetchGit, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppFetchGit_To_kappctrl_AppFetchGit(in, out, s)
}

func autoConvert_kappctrl_AppFetchGit_To_v1alpha1_AppFetchGit(in *kappctrl.AppFetchGit, out *AppFetchGit, s conversion.Scope) error {
	out.URL = in.URL
	out.Ref = in.Ref
	out.SecretRef = (*AppFetchLocalRef)(unsafe.Pointer(in.SecretRef))
	out.SubPath = in.SubPath
	out.LFSSkipSmudge = in.LFSSkipSmudge
	return nil
}

// Convert_kappctrl_AppFetchGit_To_v1alpha1_AppFetchGit is an autogenerated conversion function.
func Convert_kappctrl_AppFetchGit_To_v1alpha1_AppFetchGit(in *kappctrl.AppFetchGit, out *AppFetchGit, s conversion.Scope) error {
	return autoConvert_kappctrl_AppFetchGit_To_v1alpha1_AppFetchGit(in, out, s)
}

func autoConvert_v1alpha1_AppFetchHTTP_To_kappctrl_AppFetchHTTP(in *AppFetchHTTP, out *kappctrl.AppFetchHTTP, s conversion.Scope) error {
	out.URL = in.URL
	out.SHA256 = in.SHA256
	out.SecretRef = (*kappctrl.AppFetchLocalRef)(unsafe.Pointer(in.SecretRef))
	out.SubPath = in.SubPath
	return nil
}

// Convert_v1alpha1_AppFetchHTTP_To_kappctrl_AppFetchHTTP is an autogenerated conversion function.
func Convert_v1alpha1_AppFetchHTTP_To_kappctrl_AppFetchHTTP(in *AppFetchHTTP, out *kappctrl.AppFetchHTTP, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppFetchHTTP_To_kappctrl_AppFetchHTTP(in, out, s)
}

func autoConvert_kappctrl_AppFetchHTTP_To_v1alpha1_AppFetchHTTP(in *kappctrl.AppFetchHTTP, out *AppFetchHTTP, s conversion.Scope) error {
	out.URL = in.URL
	out.SHA256 = in.SHA256
	out.SecretRef = (*AppFetchLocalRef)(unsafe.Pointer(in.SecretRef))
	out.SubPath = in.SubPath
	return nil
}

// Convert_kappctrl_AppFetchHTTP_To_v1alpha1_AppFetchHTTP is an autogenerated conversion function.
func Convert_kappctrl_AppFetchHTTP_To_v1alpha1_AppFetchHTTP(in *kappctrl.AppFetchHTTP, out *AppFetchHTTP, s conversion.Scope) error {
	return autoConvert_kappctrl_AppFetchHTTP_To_v1alpha1_AppFetchHTTP(in, out, s)
}

func autoConvert_v1alpha1_AppFetchHelmChart_To_kappctrl_AppFetchHelmChart(in *AppFetchHelmChart, out *kappctrl.AppFetchHelmChart, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.Repository = (*kappctrl.AppFetchHelmChartRepo)(unsafe.Pointer(in.Repository))
	return nil
}

// Convert_v1alpha1_AppFetchHelmChart_To_kappctrl_AppFetchHelmChart is an autogenerated conversion function.
func Convert_v1alpha1_AppFetchHelmChart_To_kappctrl_AppFetchHelmChart(in *AppFetchHelmChart, out *kappctrl.AppFetchHelmChart, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppFetchHelmChart_To_kappctrl_AppFetchHelmChart(in, out, s)
}

func autoConvert_kappctrl_AppFetchHelmChart_To_v1alpha1_AppFetchHelmChart(in *kappctrl.AppFetchHelmChart, out *AppFetchHelmChart, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.Repository = (*AppFetchHelmChartRepo)(unsafe.Pointer(in.Repository))
	return nil
}

// Convert_kappctrl_AppFetchHelmChart_To_v1alpha1_AppFetchHelmChart is an autogenerated conversion function.
func Convert_kappctrl_AppFetchHelmChart_To_v1alpha1_AppFetchHelmChart(in *kappctrl.AppFetchHelmChart, out *AppFetchHelmChart, s conversion.Scope) error {
	return autoConvert_kappctrl_AppFetchHelmChart_To_v1alpha1_AppFetchHelmChart(in, out, s)
}

func autoConvert_v1alpha1_AppFetchHelmChartRepo_To_kappctrl_AppFetchHelmChartRepo(in *AppFetchHelmChartRepo, out *kappctrl.AppFetchHelmChartRepo, s conversion.Scope) error {
	out.URL = in.URL
	out.SecretRef = (*kappctrl.AppFetchLocalRef)(unsafe.Pointer(in.SecretRef))
	return nil
}

// Convert_v1alpha1_AppFetchHelmChartRepo_To_kappctrl_AppFetchHelmChartRepo is an autogenerated conversion function.
func Convert_v1alpha1_AppFetchHelmChartRepo_To_kappctrl_AppFetchHelmChartRepo(in *AppFetchHelmChartRepo, out *kappctrl.AppFetchHelmChartRepo, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppFetchHelmChartRepo_To_kappctrl_AppFetchHelmChartRepo(in, out, s)
}

func autoConvert_kappctrl_AppFetchHelmChartRepo_To_v1alpha1_AppFetchHelmChartRepo(in *kappctrl.AppFetchHelmChartRepo, out *AppFetchHelmChartRepo, s conversion.Scope) error {
	out.URL = in.URL
	out.SecretRef = (*AppFetchLocalRef)(unsafe.Pointer(in.SecretRef))
	return nil
}

// Convert_kappctrl_AppFetchHelmChartRepo_To_v1alpha1_AppFetchHelmChartRepo is an autogenerated conversion function.
func Convert_kappctrl_AppFetchHelmChartRepo_To_v1alpha1_AppFetchHelmChartRepo(in *kappctrl.AppFetchHelmChartRepo, out *AppFetchHelmChartRepo, s conversion.Scope) error {
	return autoConvert_kappctrl_AppFetchHelmChartRepo_To_v1alpha1_AppFetchHelmChartRepo(in, out, s)
}

func autoConvert_v1alpha1_AppFetchImage_To_kappctrl_AppFetchImage(in *AppFetchImage, out *kappctrl.AppFetchImage, s conversion.Scope) error {
	out.URL = in.URL
	out.SecretRef = (*kappctrl.AppFetchLocalRef)(unsafe.Pointer(in.SecretRef))
	out.SubPath = in.SubPath
	return nil
}

// Convert_v1alpha1_AppFetchImage_To_kappctrl_AppFetchImage is an autogenerated conversion function.
func Convert_v1alpha1_AppFetchImage_To_kappctrl_AppFetchImage(in *AppFetchImage, out *kappctrl.AppFetchImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppFetchImage_To_kappctrl_AppFetchImage(in, out, s)
}

func autoConvert_kappctrl_AppFetchImage_To_v1alpha1_AppFetchImage(in *kappctrl.AppFetchImage, out *AppFetchImage, s conversion.Scope) error {
	out.URL = in.URL
	out.SecretRef = (*AppFetchLocalRef)(unsafe.Pointer(in.SecretRef))
	out.SubPath = in.SubPath
	return nil
}

// Convert_kappctrl_AppFetchImage_To_v1alpha1_AppFetchImage is an autogenerated conversion function.
func Convert_kappctrl_AppFetchImage_To_v1alpha1_AppFetchImage(in *kappctrl.AppFetchImage, out *AppFetchImage, s conversion.Scope) error {
	return autoConvert_kappctrl_AppFetchImage_To_v1alpha1_AppFetchImage(in, out, s)
}

func autoConvert_v1alpha1_AppFetchInline_To_kappctrl_AppFetchInline(in *AppFetchInline, out *kappctrl.AppFetchInline, s conversion.Scope) error {
	out.Paths = *(*map[string]string)(unsafe.Pointer(&in.Paths))
	out.PathsFrom = *(*[]kappctrl.AppFetchInlineSource)(unsafe.Pointer(&in.PathsFrom))
	return nil
}

// Convert_v1alpha1_AppFetchInline_To_kappctrl_AppFetchInline is an autogenerated conversion function.
func Convert_v1alpha1_AppFetchInline_To_kappctrl_AppFetchInline(in *AppFetchInline, out *kappctrl.AppFetchInline, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppFetchInline_To_kappctrl_AppFetchInline(in, out, s)
}

func autoConvert_kappctrl_AppFetchInline_To_v1alpha1_AppFetchInline(in *kappctrl.AppFetchInline, out *AppFetchInline, s conversion.Scope) error {
	out.Paths = *(*map[string]string)(unsafe.Pointer(&in.Paths))
	out.PathsFrom = *(*[]AppFetchInlineSource)(unsafe.Pointer(&in.PathsFrom))
	return nil
}

// Convert_kappctrl_AppFetchInline_To_v1alpha1_AppFetchInline is an autogenerated conversion function.
func Convert_kappctrl_AppFetchInline_To_v1alpha1_AppFetchInline(in *kappctrl.AppFetchInline, out *AppFetchInline, s conversion.Scope) error {
	return autoConvert_kappctrl_AppFetchInline_To_v1alpha1_AppFetchInline(in, out, s)
}

func autoConvert_v1alpha1_AppFetchInlineSource_To_kappctrl_AppFetchInlineSource(in *AppFetchInlineSource, out *kappctrl.AppFetchInlineSource, s conversion.Scope) error {
	out.SecretRef = (*kappctrl.AppFetchInlineSourceRef)(unsafe.Pointer(in.SecretRef))
	out.ConfigMapRef = (*kappctrl.AppFetchInlineSourceRef)(unsafe.Pointer(in.ConfigMapRef))
	return nil
}

// Convert_v1alpha1_AppFetchInlineSource_To_kappctrl_AppFetchInlineSource is an autogenerated conversion function.
func Convert_v1alpha1_AppFetchInlineSource_To_kappctrl_AppFetchInlineSource(in *AppFetchInlineSource, out *kappctrl.AppFetchInlineSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppFetchInlineSource_To_kappctrl_AppFetchInlineSource(in, out, s)
}

func autoConvert_kappctrl_AppFetchInlineSource_To_v1alpha1_AppFetchInlineSource(in *kappctrl.AppFetchInlineSource, out *AppFetchInlineSource, s conversion.Scope) error {
	out.SecretRef = (*AppFetchInlineSourceRef)(unsafe.Pointer(in.SecretRef))
	out.ConfigMapRef = (*AppFetchInlineSourceRef)(unsafe.Pointer(in.ConfigMapRef))
	return nil
}

// Convert_kappctrl_AppFetchInlineSource_To_v1alpha1_AppFetchInlineSource is an autogenerated conversion function.
func Convert_kappctrl_AppFetchInlineSource_To_v1alpha1_AppFetchInlineSource(in *kappctrl.AppFetchInlineSource, out *AppFetchInlineSource, s conversion.Scope) error {
	return autoConvert_kappctrl_AppFetchInlineSource_To_v1alpha1_AppFetchInlineSource(in, out, s)
}

func autoConvert_v1alpha1_AppFetchInlineSourceRef_To_kappctrl_AppFetchInlineSourceRef(in *AppFetchInlineSourceRef, out *kappctrl.AppFetchInlineSourceRef, s conversion.Scope) error {
	out.DirectoryPath = in.DirectoryPath
	out.LocalObjectReference = in.LocalObjectReference
	return nil
}

// Convert_v1alpha1_AppFetchInlineSourceRef_To_kappctrl_AppFetchInlineSourceRef is an autogenerated conversion function.
func Convert_v1alpha1_AppFetchInlineSourceRef_To_kappctrl_AppFetchInlineSourceRef(in *AppFetchInlineSourceRef, out *kappctrl.AppFetchInlineSourceRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppFetchInlineSourceRef_To_kappctrl_AppFetchInlineSourceRef(in, out, s)
}

func autoConvert_kappctrl_AppFetchInlineSourceRef_To_v1alpha1_AppFetchInlineSourceRef(in *kappctrl.AppFetchInlineSourceRef, out *AppFetchInlineSourceRef, s conversion.Scope) error {
	out.DirectoryPath = in.DirectoryPath
	out.LocalObjectReference = in.LocalObjectReference
	return nil
}

// Convert_kappctrl_AppFetchInlineSourceRef_To_v1alpha1_AppFetchInlineSourceRef is an autogenerated conversion function.
func Convert_kappctrl_AppFetchInlineSourceRef_To_v1alpha1_AppFetchInlineSourceRef(in *kappctrl.AppFetchInlineSourceRef, out *AppFetchInlineSourceRef, s conversion.Scope) error {
	return autoConvert_kappctrl_AppFetchInlineSourceRef_To_v1alpha1_AppFetchInlineSourceRef(in, out, s)
}

func autoConvert_v1alpha1_AppFetchLocalRef_To_kappctrl_AppFetchLocalRef(in *AppFetchLocalRef, out *kappctrl.AppFetchLocalRef, s conversion.Scope) error {
	out.LocalObjectReference = in.LocalObjectReference
	return nil
}

// Convert_v1alpha1_AppFetchLocalRef_To_kappctrl_AppFetchLocalRef is an autogenerated conversion function.
func Convert_v1alpha1_AppFetchLocalRef_To_kappctrl_AppFetchLocalRef(in *AppFetchLocalRef, out *kappctrl.AppFetchLocalRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppFetchLocalRef_To_kappctrl_AppFetchLocalRef(in, out, s)
}

func autoConvert_kappctrl_AppFetchLocalRef_To_v1alpha1_AppFetchLocalRef(in *kappctrl.AppFetchLocalRef, out *AppFetchLocalRef, s conversion.Scope) error {
	out.LocalObjectReference = in.LocalObjectReference
	return nil
}

// Convert_kappctrl_AppFetchLocalRef_To_v1alpha1_AppFetchLocalRef is an autogenerated conversion function.
func Convert_kappctrl_AppFetchLocalRef_To_v1alpha1_AppFetchLocalRef(in *kappctrl.AppFetchLocalRef, out *AppFetchLocalRef, s conversion.Scope) error {
	return autoConvert_kappctrl_AppFetchLocalRef_To_v1alpha1_AppFetchLocalRef(in, out, s)
}

func autoConvert_v1alpha1_AppList_To_kappctrl_AppList(in *AppList, out *kappctrl.AppList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]kappctrl.App)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_AppList_To_kappctrl_AppList is an autogenerated conversion function.
func Convert_v1alpha1_AppList_To_kappctrl_AppList(in *AppList, out *kappctrl.AppList, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppList_To_kappctrl_AppList(in, out, s)
}

func autoConvert_kappctrl_AppList_To_v1alpha1_AppList(in *kappctrl.AppList, out *AppList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]App)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_kappctrl_AppList_To_v1alpha1_AppList is an autogenerated conversion function.
func Convert_kappctrl_AppList_To_v1alpha1_AppList(in *kappctrl.AppList, out *AppList, s conversion.Scope) error {
	return autoConvert_kappctrl_AppList_To_v1alpha1_AppList(in, out, s)
}

func autoConvert_v1alpha1_AppSpec_To_kappctrl_AppSpec(in *AppSpec, out *kappctrl.AppSpec, s conversion.Scope) error {
	out.ServiceAccountName = in.ServiceAccountName
	out.Cluster = (*kappctrl.AppCluster)(unsafe.Pointer(in.Cluster))
	out.Fetch = *(*[]kappctrl.AppFetch)(unsafe.Pointer(&in.Fetch))
	out.Template = *(*[]kappctrl.AppTemplate)(unsafe.Pointer(&in.Template))
	out.Deploy = *(*[]kappctrl.AppDeploy)(unsafe.Pointer(&in.Deploy))
	out.Paused = in.Paused
	out.Canceled = in.Canceled
	out.SyncPeriod = (*metav1.Duration)(unsafe.Pointer(in.SyncPeriod))
	return nil
}

// Convert_v1alpha1_AppSpec_To_kappctrl_AppSpec is an autogenerated conversion function.
func Convert_v1alpha1_AppSpec_To_kappctrl_AppSpec(in *AppSpec, out *kappctrl.AppSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppSpec_To_kappctrl_AppSpec(in, out, s)
}

func autoConvert_kappctrl_AppSpec_To_v1alpha1_AppSpec(in *kappctrl.AppSpec, out *AppSpec, s conversion.Scope) error {
	out.ServiceAccountName = in.ServiceAccountName
	out.Cluster = (*AppCluster)(unsafe.Pointer(in.Cluster))
	out.Fetch = *(*[]AppFetch)(unsafe.Pointer(&in.Fetch))
	out.Template = *(*[]AppTemplate)(unsafe.Pointer(&in.Template))
	out.Deploy = *(*[]AppDeploy)(unsafe.Pointer(&in.Deploy))
	out.Paused = in.Paused
	out.Canceled = in.Canceled
	out.SyncPeriod = (*metav1.Duration)(unsafe.Pointer(in.SyncPeriod))
	return nil
}

// Convert_kappctrl_AppSpec_To_v1alpha1_AppSpec is an autogenerated conversion function.
func Convert_kappctrl_AppSpec_To_v1alpha1_AppSpec(in *kappctrl.AppSpec, out *AppSpec, s conversion.Scope) error {
	return autoConvert_kappctrl_AppSpec_To_v1alpha1_AppSpec(in, out, s)
}

func autoConvert_v1alpha1_AppStatus_To_kappctrl_AppStatus(in *AppStatus, out *kappctrl.AppStatus, s conversion.Scope) error {
	out.ManagedAppName = in.ManagedAppName
	out.Fetch = (*kappctrl.AppStatusFetch)(unsafe.Pointer(in.Fetch))
	out.Template = (*kappctrl.AppStatusTemplate)(unsafe.Pointer(in.Template))
	out.Deploy = (*kappctrl.AppStatusDeploy)(unsafe.Pointer(in.Deploy))
	out.Inspect = (*kappctrl.AppStatusInspect)(unsafe.Pointer(in.Inspect))
	if err := Convert_v1alpha1_GenericStatus_To_kappctrl_GenericStatus(&in.GenericStatus, &out.GenericStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_AppStatus_To_kappctrl_AppStatus is an autogenerated conversion function.
func Convert_v1alpha1_AppStatus_To_kappctrl_AppStatus(in *AppStatus, out *kappctrl.AppStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppStatus_To_kappctrl_AppStatus(in, out, s)
}

func autoConvert_kappctrl_AppStatus_To_v1alpha1_AppStatus(in *kappctrl.AppStatus, out *AppStatus, s conversion.Scope) error {
	out.ManagedAppName = in.ManagedAppName
	out.Fetch = (*AppStatusFetch)(unsafe.Pointer(in.Fetch))
	out.Template = (*AppStatusTemplate)(unsafe.Pointer(in.Template))
	out.Deploy = (*AppStatusDeploy)(unsafe.Pointer(in.Deploy))
	out.Inspect = (*AppStatusInspect)(unsafe.Pointer(in.Inspect))
	if err := Convert_kappctrl_GenericStatus_To_v1alpha1_GenericStatus(&in.GenericStatus, &out.GenericStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_kappctrl_AppStatus_To_v1alpha1_AppStatus is an autogenerated conversion function.
func Convert_kappctrl_AppStatus_To_v1alpha1_AppStatus(in *kappctrl.AppStatus, out *AppStatus, s conversion.Scope) error {
	return autoConvert_kappctrl_AppStatus_To_v1alpha1_AppStatus(in, out, s)
}

func autoConvert_v1alpha1_AppStatusDeploy_To_kappctrl_AppStatusDeploy(in *AppStatusDeploy, out *kappctrl.AppStatusDeploy, s conversion.Scope) error {
	out.Stdout = in.Stdout
	out.Stderr = in.Stderr
	out.Finished = in.Finished
	out.ExitCode = in.ExitCode
	out.Error = in.Error
	out.StartedAt = in.StartedAt
	out.UpdatedAt = in.UpdatedAt
	return nil
}

// Convert_v1alpha1_AppStatusDeploy_To_kappctrl_AppStatusDeploy is an autogenerated conversion function.
func Convert_v1alpha1_AppStatusDeploy_To_kappctrl_AppStatusDeploy(in *AppStatusDeploy, out *kappctrl.AppStatusDeploy, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppStatusDeploy_To_kappctrl_AppStatusDeploy(in, out, s)
}

func autoConvert_kappctrl_AppStatusDeploy_To_v1alpha1_AppStatusDeploy(in *kappctrl.AppStatusDeploy, out *AppStatusDeploy, s conversion.Scope) error {
	out.Stdout = in.Stdout
	out.Stderr = in.Stderr
	out.Finished = in.Finished
	out.ExitCode = in.ExitCode
	out.Error = in.Error
	out.StartedAt = in.StartedAt
	out.UpdatedAt = in.UpdatedAt
	return nil
}

// Convert_kappctrl_AppStatusDeploy_To_v1alpha1_AppStatusDeploy is an autogenerated conversion function.
func Convert_kappctrl_AppStatusDeploy_To_v1alpha1_AppStatusDeploy(in *kappctrl.AppStatusDeploy, out *AppStatusDeploy, s conversion.Scope) error {
	return autoConvert_kappctrl_AppStatusDeploy_To_v1alpha1_AppStatusDeploy(in, out, s)
}

func autoConvert_v1alpha1_AppStatusFetch_To_kappctrl_AppStatusFetch(in *AppStatusFetch, out *kappctrl.AppStatusFetch, s conversion.Scope) error {
	out.Stderr = in.Stderr
	out.Stdout = in.Stdout
	out.ExitCode = in.ExitCode
	out.Error = in.Error
	out.StartedAt = in.StartedAt
	out.UpdatedAt = in.UpdatedAt
	return nil
}

// Convert_v1alpha1_AppStatusFetch_To_kappctrl_AppStatusFetch is an autogenerated conversion function.
func Convert_v1alpha1_AppStatusFetch_To_kappctrl_AppStatusFetch(in *AppStatusFetch, out *kappctrl.AppStatusFetch, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppStatusFetch_To_kappctrl_AppStatusFetch(in, out, s)
}

func autoConvert_kappctrl_AppStatusFetch_To_v1alpha1_AppStatusFetch(in *kappctrl.AppStatusFetch, out *AppStatusFetch, s conversion.Scope) error {
	out.Stderr = in.Stderr
	out.Stdout = in.Stdout
	out.ExitCode = in.ExitCode
	out.Error = in.Error
	out.StartedAt = in.StartedAt
	out.UpdatedAt = in.UpdatedAt
	return nil
}

// Convert_kappctrl_AppStatusFetch_To_v1alpha1_AppStatusFetch is an autogenerated conversion function.
func Convert_kappctrl_AppStatusFetch_To_v1alpha1_AppStatusFetch(in *kappctrl.AppStatusFetch, out *AppStatusFetch, s conversion.Scope) error {
	return autoConvert_kappctrl_AppStatusFetch_To_v1alpha1_AppStatusFetch(in, out, s)
}

func autoConvert_v1alpha1_AppStatusInspect_To_kappctrl_AppStatusInspect(in *AppStatusInspect, out *kappctrl.AppStatusInspect, s conversion.Scope) error {
	out.Stdout = in.Stdout
	out.Stderr = in.Stderr
	out.ExitCode = in.ExitCode
	out.Error = in.Error
	out.UpdatedAt = in.UpdatedAt
	return nil
}

// Convert_v1alpha1_AppStatusInspect_To_kappctrl_AppStatusInspect is an autogenerated conversion function.
func Convert_v1alpha1_AppStatusInspect_To_kappctrl_AppStatusInspect(in *AppStatusInspect, out *kappctrl.AppStatusInspect, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppStatusInspect_To_kappctrl_AppStatusInspect(in, out, s)
}

func autoConvert_kappctrl_AppStatusInspect_To_v1alpha1_AppStatusInspect(in *kappctrl.AppStatusInspect, out *AppStatusInspect, s conversion.Scope) error {
	out.Stdout = in.Stdout
	out.Stderr = in.Stderr
	out.ExitCode = in.ExitCode
	out.Error = in.Error
	out.UpdatedAt = in.UpdatedAt
	return nil
}

// Convert_kappctrl_AppStatusInspect_To_v1alpha1_AppStatusInspect is an autogenerated conversion function.
func Convert_kappctrl_AppStatusInspect_To_v1alpha1_AppStatusInspect(in *kappctrl.AppStatusInspect, out *AppStatusInspect, s conversion.Scope) error {
	return autoConvert_kappctrl_AppStatusInspect_To_v1alpha1_AppStatusInspect(in, out, s)
}

func autoConvert_v1alpha1_AppStatusTemplate_To_kappctrl_AppStatusTemplate(in *AppStatusTemplate, out *kappctrl.AppStatusTemplate, s conversion.Scope) error {
	out.Stderr = in.Stderr
	out.ExitCode = in.ExitCode
	out.Error = in.Error
	out.UpdatedAt = in.UpdatedAt
	return nil
}

// Convert_v1alpha1_AppStatusTemplate_To_kappctrl_AppStatusTemplate is an autogenerated conversion function.
func Convert_v1alpha1_AppStatusTemplate_To_kappctrl_AppStatusTemplate(in *AppStatusTemplate, out *kappctrl.AppStatusTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppStatusTemplate_To_kappctrl_AppStatusTemplate(in, out, s)
}

func autoConvert_kappctrl_AppStatusTemplate_To_v1alpha1_AppStatusTemplate(in *kappctrl.AppStatusTemplate, out *AppStatusTemplate, s conversion.Scope) error {
	out.Stderr = in.Stderr
	out.ExitCode = in.ExitCode
	out.Error = in.Error
	out.UpdatedAt = in.UpdatedAt
	return nil
}

// Convert_kappctrl_AppStatusTemplate_To_v1alpha1_AppStatusTemplate is an autogenerated conversion function.
func Convert_kappctrl_AppStatusTemplate_To_v1alpha1_AppStatusTemplate(in *kappctrl.AppStatusTemplate, out *AppStatusTemplate, s conversion.Scope) error {
	return autoConvert_kappctrl_AppStatusTemplate_To_v1alpha1_AppStatusTemplate(in, out, s)
}

func autoConvert_v1alpha1_AppTemplate_To_kappctrl_AppTemplate(in *AppTemplate, out *kappctrl.AppTemplate, s conversion.Scope) error {
	out.Ytt = (*kappctrl.AppTemplateYtt)(unsafe.Pointer(in.Ytt))
	out.Kbld = (*kappctrl.AppTemplateKbld)(unsafe.Pointer(in.Kbld))
	out.HelmTemplate = (*kappctrl.AppTemplateHelmTemplate)(unsafe.Pointer(in.HelmTemplate))
	out.Kustomize = (*kappctrl.AppTemplateKustomize)(unsafe.Pointer(in.Kustomize))
	out.Jsonnet = (*kappctrl.AppTemplateJsonnet)(unsafe.Pointer(in.Jsonnet))
	out.Sops = (*kappctrl.AppTemplateSops)(unsafe.Pointer(in.Sops))
	return nil
}

// Convert_v1alpha1_AppTemplate_To_kappctrl_AppTemplate is an autogenerated conversion function.
func Convert_v1alpha1_AppTemplate_To_kappctrl_AppTemplate(in *AppTemplate, out *kappctrl.AppTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppTemplate_To_kappctrl_AppTemplate(in, out, s)
}

func autoConvert_kappctrl_AppTemplate_To_v1alpha1_AppTemplate(in *kappctrl.AppTemplate, out *AppTemplate, s conversion.Scope) error {
	out.Ytt = (*AppTemplateYtt)(unsafe.Pointer(in.Ytt))
	out.Kbld = (*AppTemplateKbld)(unsafe.Pointer(in.Kbld))
	out.HelmTemplate = (*AppTemplateHelmTemplate)(unsafe.Pointer(in.HelmTemplate))
	out.Kustomize = (*AppTemplateKustomize)(unsafe.Pointer(in.Kustomize))
	out.Jsonnet = (*AppTemplateJsonnet)(unsafe.Pointer(in.Jsonnet))
	out.Sops = (*AppTemplateSops)(unsafe.Pointer(in.Sops))
	return nil
}

// Convert_kappctrl_AppTemplate_To_v1alpha1_AppTemplate is an autogenerated conversion function.
func Convert_kappctrl_AppTemplate_To_v1alpha1_AppTemplate(in *kappctrl.AppTemplate, out *AppTemplate, s conversion.Scope) error {
	return autoConvert_kappctrl_AppTemplate_To_v1alpha1_AppTemplate(in, out, s)
}

func autoConvert_v1alpha1_AppTemplateHelmTemplate_To_kappctrl_AppTemplateHelmTemplate(in *AppTemplateHelmTemplate, out *kappctrl.AppTemplateHelmTemplate, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Path = in.Path
	out.ValuesFrom = *(*[]kappctrl.AppTemplateHelmTemplateValuesSource)(unsafe.Pointer(&in.ValuesFrom))
	return nil
}

// Convert_v1alpha1_AppTemplateHelmTemplate_To_kappctrl_AppTemplateHelmTemplate is an autogenerated conversion function.
func Convert_v1alpha1_AppTemplateHelmTemplate_To_kappctrl_AppTemplateHelmTemplate(in *AppTemplateHelmTemplate, out *kappctrl.AppTemplateHelmTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppTemplateHelmTemplate_To_kappctrl_AppTemplateHelmTemplate(in, out, s)
}

func autoConvert_kappctrl_AppTemplateHelmTemplate_To_v1alpha1_AppTemplateHelmTemplate(in *kappctrl.AppTemplateHelmTemplate, out *AppTemplateHelmTemplate, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Path = in.Path
	out.ValuesFrom = *(*[]AppTemplateHelmTemplateValuesSource)(unsafe.Pointer(&in.ValuesFrom))
	return nil
}

// Convert_kappctrl_AppTemplateHelmTemplate_To_v1alpha1_AppTemplateHelmTemplate is an autogenerated conversion function.
func Convert_kappctrl_AppTemplateHelmTemplate_To_v1alpha1_AppTemplateHelmTemplate(in *kappctrl.AppTemplateHelmTemplate, out *AppTemplateHelmTemplate, s conversion.Scope) error {
	return autoConvert_kappctrl_AppTemplateHelmTemplate_To_v1alpha1_AppTemplateHelmTemplate(in, out, s)
}

func autoConvert_v1alpha1_AppTemplateHelmTemplateValuesSource_To_kappctrl_AppTemplateHelmTemplateValuesSource(in *AppTemplateHelmTemplateValuesSource, out *kappctrl.AppTemplateHelmTemplateValuesSource, s conversion.Scope) error {
	out.SecretRef = (*kappctrl.AppTemplateHelmTemplateValuesSourceRef)(unsafe.Pointer(in.SecretRef))
	out.ConfigMapRef = (*kappctrl.AppTemplateHelmTemplateValuesSourceRef)(unsafe.Pointer(in.ConfigMapRef))
	out.Path = in.Path
	return nil
}

// Convert_v1alpha1_AppTemplateHelmTemplateValuesSource_To_kappctrl_AppTemplateHelmTemplateValuesSource is an autogenerated conversion function.
func Convert_v1alpha1_AppTemplateHelmTemplateValuesSource_To_kappctrl_AppTemplateHelmTemplateValuesSource(in *AppTemplateHelmTemplateValuesSource, out *kappctrl.AppTemplateHelmTemplateValuesSource, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppTemplateHelmTemplateValuesSource_To_kappctrl_AppTemplateHelmTemplateValuesSource(in, out, s)
}

func autoConvert_kappctrl_AppTemplateHelmTemplateValuesSource_To_v1alpha1_AppTemplateHelmTemplateValuesSource(in *kappctrl.AppTemplateHelmTemplateValuesSource, out *AppTemplateHelmTemplateValuesSource, s conversion.Scope) error {
	out.SecretRef = (*AppTemplateHelmTemplateValuesSourceRef)(unsafe.Pointer(in.SecretRef))
	out.ConfigMapRef = (*AppTemplateHelmTemplateValuesSourceRef)(unsafe.Pointer(in.ConfigMapRef))
	out.Path = in.Path
	return nil
}

// Convert_kappctrl_AppTemplateHelmTemplateValuesSource_To_v1alpha1_AppTemplateHelmTemplateValuesSource is an autogenerated conversion function.
func Convert_kappctrl_AppTemplateHelmTemplateValuesSource_To_v1alpha1_AppTemplateHelmTemplateValuesSource(in *kappctrl.AppTemplateHelmTemplateValuesSource, out *AppTemplateHelmTemplateValuesSource, s conversion.Scope) error {
	return autoConvert_kappctrl_AppTemplateHelmTemplateValuesSource_To_v1alpha1_AppTemplateHelmTemplateValuesSource(in, out, s)
}

func autoConvert_v1alpha1_AppTemplateHelmTemplateValuesSourceRef_To_kappctrl_AppTemplateHelmTemplateValuesSourceRef(in *AppTemplateHelmTemplateValuesSourceRef, out *kappctrl.AppTemplateHelmTemplateValuesSourceRef, s conversion.Scope) error {
	out.LocalObjectReference = in.LocalObjectReference
	return nil
}

// Convert_v1alpha1_AppTemplateHelmTemplateValuesSourceRef_To_kappctrl_AppTemplateHelmTemplateValuesSourceRef is an autogenerated conversion function.
func Convert_v1alpha1_AppTemplateHelmTemplateValuesSourceRef_To_kappctrl_AppTemplateHelmTemplateValuesSourceRef(in *AppTemplateHelmTemplateValuesSourceRef, out *kappctrl.AppTemplateHelmTemplateValuesSourceRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppTemplateHelmTemplateValuesSourceRef_To_kappctrl_AppTemplateHelmTemplateValuesSourceRef(in, out, s)
}

func autoConvert_kappctrl_AppTemplateHelmTemplateValuesSourceRef_To_v1alpha1_AppTemplateHelmTemplateValuesSourceRef(in *kappctrl.AppTemplateHelmTemplateValuesSourceRef, out *AppTemplateHelmTemplateValuesSourceRef, s conversion.Scope) error {
	out.LocalObjectReference = in.LocalObjectReference
	return nil
}

// Convert_kappctrl_AppTemplateHelmTemplateValuesSourceRef_To_v1alpha1_AppTemplateHelmTemplateValuesSourceRef is an autogenerated conversion function.
func Convert_kappctrl_AppTemplateHelmTemplateValuesSourceRef_To_v1alpha1_AppTemplateHelmTemplateValuesSourceRef(in *kappctrl.AppTemplateHelmTemplateValuesSourceRef, out *AppTemplateHelmTemplateValuesSourceRef, s conversion.Scope) error {
	return autoConvert_kappctrl_AppTemplateHelmTemplateValuesSourceRef_To_v1alpha1_AppTemplateHelmTemplateValuesSourceRef(in, out, s)
}

func autoConvert_v1alpha1_AppTemplateJsonnet_To_kappctrl_AppTemplateJsonnet(in *AppTemplateJsonnet, out *kappctrl.AppTemplateJsonnet, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_AppTemplateJsonnet_To_kappctrl_AppTemplateJsonnet is an autogenerated conversion function.
func Convert_v1alpha1_AppTemplateJsonnet_To_kappctrl_AppTemplateJsonnet(in *AppTemplateJsonnet, out *kappctrl.AppTemplateJsonnet, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppTemplateJsonnet_To_kappctrl_AppTemplateJsonnet(in, out, s)
}

func autoConvert_kappctrl_AppTemplateJsonnet_To_v1alpha1_AppTemplateJsonnet(in *kappctrl.AppTemplateJsonnet, out *AppTemplateJsonnet, s conversion.Scope) error {
	return nil
}

// Convert_kappctrl_AppTemplateJsonnet_To_v1alpha1_AppTemplateJsonnet is an autogenerated conversion function.
func Convert_kappctrl_AppTemplateJsonnet_To_v1alpha1_AppTemplateJsonnet(in *kappctrl.AppTemplateJsonnet, out *AppTemplateJsonnet, s conversion.Scope) error {
	return autoConvert_kappctrl_AppTemplateJsonnet_To_v1alpha1_AppTemplateJsonnet(in, out, s)
}

func autoConvert_v1alpha1_AppTemplateKbld_To_kappctrl_AppTemplateKbld(in *AppTemplateKbld, out *kappctrl.AppTemplateKbld, s conversion.Scope) error {
	out.Paths = *(*[]string)(unsafe.Pointer(&in.Paths))
	return nil
}

// Convert_v1alpha1_AppTemplateKbld_To_kappctrl_AppTemplateKbld is an autogenerated conversion function.
func Convert_v1alpha1_AppTemplateKbld_To_kappctrl_AppTemplateKbld(in *AppTemplateKbld, out *kappctrl.AppTemplateKbld, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppTemplateKbld_To_kappctrl_AppTemplateKbld(in, out, s)
}

func autoConvert_kappctrl_AppTemplateKbld_To_v1alpha1_AppTemplateKbld(in *kappctrl.AppTemplateKbld, out *AppTemplateKbld, s conversion.Scope) error {
	out.Paths = *(*[]string)(unsafe.Pointer(&in.Paths))
	return nil
}

// Convert_kappctrl_AppTemplateKbld_To_v1alpha1_AppTemplateKbld is an autogenerated conversion function.
func Convert_kappctrl_AppTemplateKbld_To_v1alpha1_AppTemplateKbld(in *kappctrl.AppTemplateKbld, out *AppTemplateKbld, s conversion.Scope) error {
	return autoConvert_kappctrl_AppTemplateKbld_To_v1alpha1_AppTemplateKbld(in, out, s)
}

func autoConvert_v1alpha1_AppTemplateKustomize_To_kappctrl_AppTemplateKustomize(in *AppTemplateKustomize, out *kappctrl.AppTemplateKustomize, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_AppTemplateKustomize_To_kappctrl_AppTemplateKustomize is an autogenerated conversion function.
func Convert_v1alpha1_AppTemplateKustomize_To_kappctrl_AppTemplateKustomize(in *AppTemplateKustomize, out *kappctrl.AppTemplateKustomize, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppTemplateKustomize_To_kappctrl_AppTemplateKustomize(in, out, s)
}

func autoConvert_kappctrl_AppTemplateKustomize_To_v1alpha1_AppTemplateKustomize(in *kappctrl.AppTemplateKustomize, out *AppTemplateKustomize, s conversion.Scope) error {
	return nil
}

// Convert_kappctrl_AppTemplateKustomize_To_v1alpha1_AppTemplateKustomize is an autogenerated conversion function.
func Convert_kappctrl_AppTemplateKustomize_To_v1alpha1_AppTemplateKustomize(in *kappctrl.AppTemplateKustomize, out *AppTemplateKustomize, s conversion.Scope) error {
	return autoConvert_kappctrl_AppTemplateKustomize_To_v1alpha1_AppTemplateKustomize(in, out, s)
}

func autoConvert_v1alpha1_AppTemplateSops_To_kappctrl_AppTemplateSops(in *AppTemplateSops, out *kappctrl.AppTemplateSops, s conversion.Scope) error {
	out.PGP = (*kappctrl.AppTemplateSopsPGP)(unsafe.Pointer(in.PGP))
	out.Paths = *(*[]string)(unsafe.Pointer(&in.Paths))
	return nil
}

// Convert_v1alpha1_AppTemplateSops_To_kappctrl_AppTemplateSops is an autogenerated conversion function.
func Convert_v1alpha1_AppTemplateSops_To_kappctrl_AppTemplateSops(in *AppTemplateSops, out *kappctrl.AppTemplateSops, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppTemplateSops_To_kappctrl_AppTemplateSops(in, out, s)
}

func autoConvert_kappctrl_AppTemplateSops_To_v1alpha1_AppTemplateSops(in *kappctrl.AppTemplateSops, out *AppTemplateSops, s conversion.Scope) error {
	out.PGP = (*AppTemplateSopsPGP)(unsafe.Pointer(in.PGP))
	out.Paths = *(*[]string)(unsafe.Pointer(&in.Paths))
	return nil
}

// Convert_kappctrl_AppTemplateSops_To_v1alpha1_AppTemplateSops is an autogenerated conversion function.
func Convert_kappctrl_AppTemplateSops_To_v1alpha1_AppTemplateSops(in *kappctrl.AppTemplateSops, out *AppTemplateSops, s conversion.Scope) error {
	return autoConvert_kappctrl_AppTemplateSops_To_v1alpha1_AppTemplateSops(in, out, s)
}

func autoConvert_v1alpha1_AppTemplateSopsPGP_To_kappctrl_AppTemplateSopsPGP(in *AppTemplateSopsPGP, out *kappctrl.AppTemplateSopsPGP, s conversion.Scope) error {
	out.PrivateKeysSecretRef = (*kappctrl.AppTemplateSopsPGPPrivateKeysSecretRef)(unsafe.Pointer(in.PrivateKeysSecretRef))
	return nil
}

// Convert_v1alpha1_AppTemplateSopsPGP_To_kappctrl_AppTemplateSopsPGP is an autogenerated conversion function.
func Convert_v1alpha1_AppTemplateSopsPGP_To_kappctrl_AppTemplateSopsPGP(in *AppTemplateSopsPGP, out *kappctrl.AppTemplateSopsPGP, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppTemplateSopsPGP_To_kappctrl_AppTemplateSopsPGP(in, out, s)
}

func autoConvert_kappctrl_AppTemplateSopsPGP_To_v1alpha1_AppTemplateSopsPGP(in *kappctrl.AppTemplateSopsPGP, out *AppTemplateSopsPGP, s conversion.Scope) error {
	out.PrivateKeysSecretRef = (*AppTemplateSopsPGPPrivateKeysSecretRef)(unsafe.Pointer(in.PrivateKeysSecretRef))
	return nil
}

// Convert_kappctrl_AppTemplateSopsPGP_To_v1alpha1_AppTemplateSopsPGP is an autogenerated conversion function.
func Convert_kappctrl_AppTemplateSopsPGP_To_v1alpha1_AppTemplateSopsPGP(in *kappctrl.AppTemplateSopsPGP, out *AppTemplateSopsPGP, s conversion.Scope) error {
	return autoConvert_kappctrl_AppTemplateSopsPGP_To_v1alpha1_AppTemplateSopsPGP(in, out, s)
}

func autoConvert_v1alpha1_AppTemplateSopsPGPPrivateKeysSecretRef_To_kappctrl_AppTemplateSopsPGPPrivateKeysSecretRef(in *AppTemplateSopsPGPPrivateKeysSecretRef, out *kappctrl.AppTemplateSopsPGPPrivateKeysSecretRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_AppTemplateSopsPGPPrivateKeysSecretRef_To_kappctrl_AppTemplateSopsPGPPrivateKeysSecretRef is an autogenerated conversion function.
func Convert_v1alpha1_AppTemplateSopsPGPPrivateKeysSecretRef_To_kappctrl_AppTemplateSopsPGPPrivateKeysSecretRef(in *AppTemplateSopsPGPPrivateKeysSecretRef, out *kappctrl.AppTemplateSopsPGPPrivateKeysSecretRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppTemplateSopsPGPPrivateKeysSecretRef_To_kappctrl_AppTemplateSopsPGPPrivateKeysSecretRef(in, out, s)
}

func autoConvert_kappctrl_AppTemplateSopsPGPPrivateKeysSecretRef_To_v1alpha1_AppTemplateSopsPGPPrivateKeysSecretRef(in *kappctrl.AppTemplateSopsPGPPrivateKeysSecretRef, out *AppTemplateSopsPGPPrivateKeysSecretRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_kappctrl_AppTemplateSopsPGPPrivateKeysSecretRef_To_v1alpha1_AppTemplateSopsPGPPrivateKeysSecretRef is an autogenerated conversion function.
func Convert_kappctrl_AppTemplateSopsPGPPrivateKeysSecretRef_To_v1alpha1_AppTemplateSopsPGPPrivateKeysSecretRef(in *kappctrl.AppTemplateSopsPGPPrivateKeysSecretRef, out *AppTemplateSopsPGPPrivateKeysSecretRef, s conversion.Scope) error {
	return autoConvert_kappctrl_AppTemplateSopsPGPPrivateKeysSecretRef_To_v1alpha1_AppTemplateSopsPGPPrivateKeysSecretRef(in, out, s)
}

func autoConvert_v1alpha1_AppTemplateYtt_To_kappctrl_AppTemplateYtt(in *AppTemplateYtt, out *kappctrl.AppTemplateYtt, s conversion.Scope) error {
	out.IgnoreUnknownComments = in.IgnoreUnknownComments
	out.Strict = in.Strict
	out.Inline = (*kappctrl.AppFetchInline)(unsafe.Pointer(in.Inline))
	out.Paths = *(*[]string)(unsafe.Pointer(&in.Paths))
	return nil
}

// Convert_v1alpha1_AppTemplateYtt_To_kappctrl_AppTemplateYtt is an autogenerated conversion function.
func Convert_v1alpha1_AppTemplateYtt_To_kappctrl_AppTemplateYtt(in *AppTemplateYtt, out *kappctrl.AppTemplateYtt, s conversion.Scope) error {
	return autoConvert_v1alpha1_AppTemplateYtt_To_kappctrl_AppTemplateYtt(in, out, s)
}

func autoConvert_kappctrl_AppTemplateYtt_To_v1alpha1_AppTemplateYtt(in *kappctrl.AppTemplateYtt, out *AppTemplateYtt, s conversion.Scope) error {
	out.IgnoreUnknownComments = in.IgnoreUnknownComments
	out.Strict = in.Strict
	out.Inline = (*AppFetchInline)(unsafe.Pointer(in.Inline))
	out.Paths = *(*[]string)(unsafe.Pointer(&in.Paths))
	return nil
}

// Convert_kappctrl_AppTemplateYtt_To_v1alpha1_AppTemplateYtt is an autogenerated conversion function.
func Convert_kappctrl_AppTemplateYtt_To_v1alpha1_AppTemplateYtt(in *kappctrl.AppTemplateYtt, out *AppTemplateYtt, s conversion.Scope) error {
	return autoConvert_kappctrl_AppTemplateYtt_To_v1alpha1_AppTemplateYtt(in, out, s)
}

func autoConvert_v1alpha1_GenericStatus_To_kappctrl_GenericStatus(in *GenericStatus, out *kappctrl.GenericStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]kappctrl.AppCondition)(unsafe.Pointer(&in.Conditions))
	out.FriendlyDescription = in.FriendlyDescription
	return nil
}

// Convert_v1alpha1_GenericStatus_To_kappctrl_GenericStatus is an autogenerated conversion function.
func Convert_v1alpha1_GenericStatus_To_kappctrl_GenericStatus(in *GenericStatus, out *kappctrl.GenericStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_GenericStatus_To_kappctrl_GenericStatus(in, out, s)
}

func autoConvert_kappctrl_GenericStatus_To_v1alpha1_GenericStatus(in *kappctrl.GenericStatus, out *GenericStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]AppCondition)(unsafe.Pointer(&in.Conditions))
	out.FriendlyDescription = in.FriendlyDescription
	return nil
}

// Convert_kappctrl_GenericStatus_To_v1alpha1_GenericStatus is an autogenerated conversion function.
func Convert_kappctrl_GenericStatus_To_v1alpha1_GenericStatus(in *kappctrl.GenericStatus, out *GenericStatus, s conversion.Scope) error {
	return autoConvert_kappctrl_GenericStatus_To_v1alpha1_GenericStatus(in, out, s)
}

func autoConvert_v1alpha1_InstalledPkg_To_kappctrl_InstalledPkg(in *InstalledPkg, out *kappctrl.InstalledPkg, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_InstalledPkgSpec_To_kappctrl_InstalledPkgSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_InstalledPkgStatus_To_kappctrl_InstalledPkgStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_InstalledPkg_To_kappctrl_InstalledPkg is an autogenerated conversion function.
func Convert_v1alpha1_InstalledPkg_To_kappctrl_InstalledPkg(in *InstalledPkg, out *kappctrl.InstalledPkg, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstalledPkg_To_kappctrl_InstalledPkg(in, out, s)
}

func autoConvert_kappctrl_InstalledPkg_To_v1alpha1_InstalledPkg(in *kappctrl.InstalledPkg, out *InstalledPkg, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_kappctrl_InstalledPkgSpec_To_v1alpha1_InstalledPkgSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_kappctrl_InstalledPkgStatus_To_v1alpha1_InstalledPkgStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_kappctrl_InstalledPkg_To_v1alpha1_InstalledPkg is an autogenerated conversion function.
func Convert_kappctrl_InstalledPkg_To_v1alpha1_InstalledPkg(in *kappctrl.InstalledPkg, out *InstalledPkg, s conversion.Scope) error {
	return autoConvert_kappctrl_InstalledPkg_To_v1alpha1_InstalledPkg(in, out, s)
}

func autoConvert_v1alpha1_InstalledPkgList_To_kappctrl_InstalledPkgList(in *InstalledPkgList, out *kappctrl.InstalledPkgList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]kappctrl.InstalledPkg)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_InstalledPkgList_To_kappctrl_InstalledPkgList is an autogenerated conversion function.
func Convert_v1alpha1_InstalledPkgList_To_kappctrl_InstalledPkgList(in *InstalledPkgList, out *kappctrl.InstalledPkgList, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstalledPkgList_To_kappctrl_InstalledPkgList(in, out, s)
}

func autoConvert_kappctrl_InstalledPkgList_To_v1alpha1_InstalledPkgList(in *kappctrl.InstalledPkgList, out *InstalledPkgList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]InstalledPkg)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_kappctrl_InstalledPkgList_To_v1alpha1_InstalledPkgList is an autogenerated conversion function.
func Convert_kappctrl_InstalledPkgList_To_v1alpha1_InstalledPkgList(in *kappctrl.InstalledPkgList, out *InstalledPkgList, s conversion.Scope) error {
	return autoConvert_kappctrl_InstalledPkgList_To_v1alpha1_InstalledPkgList(in, out, s)
}

func autoConvert_v1alpha1_InstalledPkgPkgRef_To_kappctrl_InstalledPkgPkgRef(in *InstalledPkgPkgRef, out *kappctrl.InstalledPkgPkgRef, s conversion.Scope) error {
	out.PublicName = in.PublicName
	out.Version = in.Version
	out.VersionSelection = (*versionsv1alpha1.VersionSelectionSemver)(unsafe.Pointer(in.VersionSelection))
	return nil
}

// Convert_v1alpha1_InstalledPkgPkgRef_To_kappctrl_InstalledPkgPkgRef is an autogenerated conversion function.
func Convert_v1alpha1_InstalledPkgPkgRef_To_kappctrl_InstalledPkgPkgRef(in *InstalledPkgPkgRef, out *kappctrl.InstalledPkgPkgRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstalledPkgPkgRef_To_kappctrl_InstalledPkgPkgRef(in, out, s)
}

func autoConvert_kappctrl_InstalledPkgPkgRef_To_v1alpha1_InstalledPkgPkgRef(in *kappctrl.InstalledPkgPkgRef, out *InstalledPkgPkgRef, s conversion.Scope) error {
	out.PublicName = in.PublicName
	out.Version = in.Version
	out.VersionSelection = (*versionsv1alpha1.VersionSelectionSemver)(unsafe.Pointer(in.VersionSelection))
	return nil
}

// Convert_kappctrl_InstalledPkgPkgRef_To_v1alpha1_InstalledPkgPkgRef is an autogenerated conversion function.
func Convert_kappctrl_InstalledPkgPkgRef_To_v1alpha1_InstalledPkgPkgRef(in *kappctrl.InstalledPkgPkgRef, out *InstalledPkgPkgRef, s conversion.Scope) error {
	return autoConvert_kappctrl_InstalledPkgPkgRef_To_v1alpha1_InstalledPkgPkgRef(in, out, s)
}

func autoConvert_v1alpha1_InstalledPkgSpec_To_kappctrl_InstalledPkgSpec(in *InstalledPkgSpec, out *kappctrl.InstalledPkgSpec, s conversion.Scope) error {
	out.ServiceAccountName = in.ServiceAccountName
	out.Cluster = (*kappctrl.AppCluster)(unsafe.Pointer(in.Cluster))
	out.PkgRef = (*kappctrl.InstalledPkgPkgRef)(unsafe.Pointer(in.PkgRef))
	out.Values = *(*[]kappctrl.InstalledPkgValues)(unsafe.Pointer(&in.Values))
	return nil
}

// Convert_v1alpha1_InstalledPkgSpec_To_kappctrl_InstalledPkgSpec is an autogenerated conversion function.
func Convert_v1alpha1_InstalledPkgSpec_To_kappctrl_InstalledPkgSpec(in *InstalledPkgSpec, out *kappctrl.InstalledPkgSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstalledPkgSpec_To_kappctrl_InstalledPkgSpec(in, out, s)
}

func autoConvert_kappctrl_InstalledPkgSpec_To_v1alpha1_InstalledPkgSpec(in *kappctrl.InstalledPkgSpec, out *InstalledPkgSpec, s conversion.Scope) error {
	out.ServiceAccountName = in.ServiceAccountName
	out.Cluster = (*AppCluster)(unsafe.Pointer(in.Cluster))
	out.PkgRef = (*InstalledPkgPkgRef)(unsafe.Pointer(in.PkgRef))
	out.Values = *(*[]InstalledPkgValues)(unsafe.Pointer(&in.Values))
	return nil
}

// Convert_kappctrl_InstalledPkgSpec_To_v1alpha1_InstalledPkgSpec is an autogenerated conversion function.
func Convert_kappctrl_InstalledPkgSpec_To_v1alpha1_InstalledPkgSpec(in *kappctrl.InstalledPkgSpec, out *InstalledPkgSpec, s conversion.Scope) error {
	return autoConvert_kappctrl_InstalledPkgSpec_To_v1alpha1_InstalledPkgSpec(in, out, s)
}

func autoConvert_v1alpha1_InstalledPkgStatus_To_kappctrl_InstalledPkgStatus(in *InstalledPkgStatus, out *kappctrl.InstalledPkgStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_GenericStatus_To_kappctrl_GenericStatus(&in.GenericStatus, &out.GenericStatus, s); err != nil {
		return err
	}
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_InstalledPkgStatus_To_kappctrl_InstalledPkgStatus is an autogenerated conversion function.
func Convert_v1alpha1_InstalledPkgStatus_To_kappctrl_InstalledPkgStatus(in *InstalledPkgStatus, out *kappctrl.InstalledPkgStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstalledPkgStatus_To_kappctrl_InstalledPkgStatus(in, out, s)
}

func autoConvert_kappctrl_InstalledPkgStatus_To_v1alpha1_InstalledPkgStatus(in *kappctrl.InstalledPkgStatus, out *InstalledPkgStatus, s conversion.Scope) error {
	if err := Convert_kappctrl_GenericStatus_To_v1alpha1_GenericStatus(&in.GenericStatus, &out.GenericStatus, s); err != nil {
		return err
	}
	out.Version = in.Version
	return nil
}

// Convert_kappctrl_InstalledPkgStatus_To_v1alpha1_InstalledPkgStatus is an autogenerated conversion function.
func Convert_kappctrl_InstalledPkgStatus_To_v1alpha1_InstalledPkgStatus(in *kappctrl.InstalledPkgStatus, out *InstalledPkgStatus, s conversion.Scope) error {
	return autoConvert_kappctrl_InstalledPkgStatus_To_v1alpha1_InstalledPkgStatus(in, out, s)
}

func autoConvert_v1alpha1_InstalledPkgValues_To_kappctrl_InstalledPkgValues(in *InstalledPkgValues, out *kappctrl.InstalledPkgValues, s conversion.Scope) error {
	out.SecretRef = (*kappctrl.InstalledPkgValuesSecretRef)(unsafe.Pointer(in.SecretRef))
	return nil
}

// Convert_v1alpha1_InstalledPkgValues_To_kappctrl_InstalledPkgValues is an autogenerated conversion function.
func Convert_v1alpha1_InstalledPkgValues_To_kappctrl_InstalledPkgValues(in *InstalledPkgValues, out *kappctrl.InstalledPkgValues, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstalledPkgValues_To_kappctrl_InstalledPkgValues(in, out, s)
}

func autoConvert_kappctrl_InstalledPkgValues_To_v1alpha1_InstalledPkgValues(in *kappctrl.InstalledPkgValues, out *InstalledPkgValues, s conversion.Scope) error {
	out.SecretRef = (*InstalledPkgValuesSecretRef)(unsafe.Pointer(in.SecretRef))
	return nil
}

// Convert_kappctrl_InstalledPkgValues_To_v1alpha1_InstalledPkgValues is an autogenerated conversion function.
func Convert_kappctrl_InstalledPkgValues_To_v1alpha1_InstalledPkgValues(in *kappctrl.InstalledPkgValues, out *InstalledPkgValues, s conversion.Scope) error {
	return autoConvert_kappctrl_InstalledPkgValues_To_v1alpha1_InstalledPkgValues(in, out, s)
}

func autoConvert_v1alpha1_InstalledPkgValuesSecretRef_To_kappctrl_InstalledPkgValuesSecretRef(in *InstalledPkgValuesSecretRef, out *kappctrl.InstalledPkgValuesSecretRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1alpha1_InstalledPkgValuesSecretRef_To_kappctrl_InstalledPkgValuesSecretRef is an autogenerated conversion function.
func Convert_v1alpha1_InstalledPkgValuesSecretRef_To_kappctrl_InstalledPkgValuesSecretRef(in *InstalledPkgValuesSecretRef, out *kappctrl.InstalledPkgValuesSecretRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstalledPkgValuesSecretRef_To_kappctrl_InstalledPkgValuesSecretRef(in, out, s)
}

func autoConvert_kappctrl_InstalledPkgValuesSecretRef_To_v1alpha1_InstalledPkgValuesSecretRef(in *kappctrl.InstalledPkgValuesSecretRef, out *InstalledPkgValuesSecretRef, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_kappctrl_InstalledPkgValuesSecretRef_To_v1alpha1_InstalledPkgValuesSecretRef is an autogenerated conversion function.
func Convert_kappctrl_InstalledPkgValuesSecretRef_To_v1alpha1_InstalledPkgValuesSecretRef(in *kappctrl.InstalledPkgValuesSecretRef, out *InstalledPkgValuesSecretRef, s conversion.Scope) error {
	return autoConvert_kappctrl_InstalledPkgValuesSecretRef_To_v1alpha1_InstalledPkgValuesSecretRef(in, out, s)
}

func autoConvert_v1alpha1_PkgRepository_To_kappctrl_PkgRepository(in *PkgRepository, out *kappctrl.PkgRepository, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PkgRepositorySpec_To_kappctrl_PkgRepositorySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PkgRepositoryStatus_To_kappctrl_PkgRepositoryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PkgRepository_To_kappctrl_PkgRepository is an autogenerated conversion function.
func Convert_v1alpha1_PkgRepository_To_kappctrl_PkgRepository(in *PkgRepository, out *kappctrl.PkgRepository, s conversion.Scope) error {
	return autoConvert_v1alpha1_PkgRepository_To_kappctrl_PkgRepository(in, out, s)
}

func autoConvert_kappctrl_PkgRepository_To_v1alpha1_PkgRepository(in *kappctrl.PkgRepository, out *PkgRepository, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_kappctrl_PkgRepositorySpec_To_v1alpha1_PkgRepositorySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_kappctrl_PkgRepositoryStatus_To_v1alpha1_PkgRepositoryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_kappctrl_PkgRepository_To_v1alpha1_PkgRepository is an autogenerated conversion function.
func Convert_kappctrl_PkgRepository_To_v1alpha1_PkgRepository(in *kappctrl.PkgRepository, out *PkgRepository, s conversion.Scope) error {
	return autoConvert_kappctrl_PkgRepository_To_v1alpha1_PkgRepository(in, out, s)
}

func autoConvert_v1alpha1_PkgRepositoryFetch_To_kappctrl_PkgRepositoryFetch(in *PkgRepositoryFetch, out *kappctrl.PkgRepositoryFetch, s conversion.Scope) error {
	out.Image = (*kappctrl.AppFetchImage)(unsafe.Pointer(in.Image))
	out.HTTP = (*kappctrl.AppFetchHTTP)(unsafe.Pointer(in.HTTP))
	out.Git = (*kappctrl.AppFetchGit)(unsafe.Pointer(in.Git))
	return nil
}

// Convert_v1alpha1_PkgRepositoryFetch_To_kappctrl_PkgRepositoryFetch is an autogenerated conversion function.
func Convert_v1alpha1_PkgRepositoryFetch_To_kappctrl_PkgRepositoryFetch(in *PkgRepositoryFetch, out *kappctrl.PkgRepositoryFetch, s conversion.Scope) error {
	return autoConvert_v1alpha1_PkgRepositoryFetch_To_kappctrl_PkgRepositoryFetch(in, out, s)
}

func autoConvert_kappctrl_PkgRepositoryFetch_To_v1alpha1_PkgRepositoryFetch(in *kappctrl.PkgRepositoryFetch, out *PkgRepositoryFetch, s conversion.Scope) error {
	out.Image = (*AppFetchImage)(unsafe.Pointer(in.Image))
	out.HTTP = (*AppFetchHTTP)(unsafe.Pointer(in.HTTP))
	out.Git = (*AppFetchGit)(unsafe.Pointer(in.Git))
	return nil
}

// Convert_kappctrl_PkgRepositoryFetch_To_v1alpha1_PkgRepositoryFetch is an autogenerated conversion function.
func Convert_kappctrl_PkgRepositoryFetch_To_v1alpha1_PkgRepositoryFetch(in *kappctrl.PkgRepositoryFetch, out *PkgRepositoryFetch, s conversion.Scope) error {
	return autoConvert_kappctrl_PkgRepositoryFetch_To_v1alpha1_PkgRepositoryFetch(in, out, s)
}

func autoConvert_v1alpha1_PkgRepositoryList_To_kappctrl_PkgRepositoryList(in *PkgRepositoryList, out *kappctrl.PkgRepositoryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]kappctrl.PkgRepository)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PkgRepositoryList_To_kappctrl_PkgRepositoryList is an autogenerated conversion function.
func Convert_v1alpha1_PkgRepositoryList_To_kappctrl_PkgRepositoryList(in *PkgRepositoryList, out *kappctrl.PkgRepositoryList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PkgRepositoryList_To_kappctrl_PkgRepositoryList(in, out, s)
}

func autoConvert_kappctrl_PkgRepositoryList_To_v1alpha1_PkgRepositoryList(in *kappctrl.PkgRepositoryList, out *PkgRepositoryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]PkgRepository)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_kappctrl_PkgRepositoryList_To_v1alpha1_PkgRepositoryList is an autogenerated conversion function.
func Convert_kappctrl_PkgRepositoryList_To_v1alpha1_PkgRepositoryList(in *kappctrl.PkgRepositoryList, out *PkgRepositoryList, s conversion.Scope) error {
	return autoConvert_kappctrl_PkgRepositoryList_To_v1alpha1_PkgRepositoryList(in, out, s)
}

func autoConvert_v1alpha1_PkgRepositorySpec_To_kappctrl_PkgRepositorySpec(in *PkgRepositorySpec, out *kappctrl.PkgRepositorySpec, s conversion.Scope) error {
	out.Fetch = (*kappctrl.PkgRepositoryFetch)(unsafe.Pointer(in.Fetch))
	return nil
}

// Convert_v1alpha1_PkgRepositorySpec_To_kappctrl_PkgRepositorySpec is an autogenerated conversion function.
func Convert_v1alpha1_PkgRepositorySpec_To_kappctrl_PkgRepositorySpec(in *PkgRepositorySpec, out *kappctrl.PkgRepositorySpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PkgRepositorySpec_To_kappctrl_PkgRepositorySpec(in, out, s)
}

func autoConvert_kappctrl_PkgRepositorySpec_To_v1alpha1_PkgRepositorySpec(in *kappctrl.PkgRepositorySpec, out *PkgRepositorySpec, s conversion.Scope) error {
	out.Fetch = (*PkgRepositoryFetch)(unsafe.Pointer(in.Fetch))
	return nil
}

// Convert_kappctrl_PkgRepositorySpec_To_v1alpha1_PkgRepositorySpec is an autogenerated conversion function.
func Convert_kappctrl_PkgRepositorySpec_To_v1alpha1_PkgRepositorySpec(in *kappctrl.PkgRepositorySpec, out *PkgRepositorySpec, s conversion.Scope) error {
	return autoConvert_kappctrl_PkgRepositorySpec_To_v1alpha1_PkgRepositorySpec(in, out, s)
}

func autoConvert_v1alpha1_PkgRepositoryStatus_To_kappctrl_PkgRepositoryStatus(in *PkgRepositoryStatus, out *kappctrl.PkgRepositoryStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]kappctrl.AppCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_PkgRepositoryStatus_To_kappctrl_PkgRepositoryStatus is an autogenerated conversion function.
func Convert_v1alpha1_PkgRepositoryStatus_To_kappctrl_PkgRepositoryStatus(in *PkgRepositoryStatus, out *kappctrl.PkgRepositoryStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PkgRepositoryStatus_To_kappctrl_PkgRepositoryStatus(in, out, s)
}

func autoConvert_kappctrl_PkgRepositoryStatus_To_v1alpha1_PkgRepositoryStatus(in *kappctrl.PkgRepositoryStatus, out *PkgRepositoryStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]AppCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_kappctrl_PkgRepositoryStatus_To_v1alpha1_PkgRepositoryStatus is an autogenerated conversion function.
func Convert_kappctrl_PkgRepositoryStatus_To_v1alpha1_PkgRepositoryStatus(in *kappctrl.PkgRepositoryStatus, out *PkgRepositoryStatus, s conversion.Scope) error {
	return autoConvert_kappctrl_PkgRepositoryStatus_To_v1alpha1_PkgRepositoryStatus(in, out, s)
}
