// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	kappctrlv1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apis/kappctrl/v1alpha1"
	packages "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apis/packages"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Pkg)(nil), (*packages.Pkg)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Pkg_To_packages_Pkg(a.(*Pkg), b.(*packages.Pkg), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*packages.Pkg)(nil), (*Pkg)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_packages_Pkg_To_v1alpha1_Pkg(a.(*packages.Pkg), b.(*Pkg), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PkgList)(nil), (*packages.PkgList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PkgList_To_packages_PkgList(a.(*PkgList), b.(*packages.PkgList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*packages.PkgList)(nil), (*PkgList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_packages_PkgList_To_v1alpha1_PkgList(a.(*packages.PkgList), b.(*PkgList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PkgSpec)(nil), (*packages.PkgSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PkgSpec_To_packages_PkgSpec(a.(*PkgSpec), b.(*packages.PkgSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*packages.PkgSpec)(nil), (*PkgSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_packages_PkgSpec_To_v1alpha1_PkgSpec(a.(*packages.PkgSpec), b.(*PkgSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PkgStatus)(nil), (*packages.PkgStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PkgStatus_To_packages_PkgStatus(a.(*PkgStatus), b.(*packages.PkgStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*packages.PkgStatus)(nil), (*PkgStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_packages_PkgStatus_To_v1alpha1_PkgStatus(a.(*packages.PkgStatus), b.(*PkgStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Pkg_To_packages_Pkg(in *Pkg, out *packages.Pkg, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PkgSpec_To_packages_PkgSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PkgStatus_To_packages_PkgStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Pkg_To_packages_Pkg is an autogenerated conversion function.
func Convert_v1alpha1_Pkg_To_packages_Pkg(in *Pkg, out *packages.Pkg, s conversion.Scope) error {
	return autoConvert_v1alpha1_Pkg_To_packages_Pkg(in, out, s)
}

func autoConvert_packages_Pkg_To_v1alpha1_Pkg(in *packages.Pkg, out *Pkg, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_packages_PkgSpec_To_v1alpha1_PkgSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_packages_PkgStatus_To_v1alpha1_PkgStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_packages_Pkg_To_v1alpha1_Pkg is an autogenerated conversion function.
func Convert_packages_Pkg_To_v1alpha1_Pkg(in *packages.Pkg, out *Pkg, s conversion.Scope) error {
	return autoConvert_packages_Pkg_To_v1alpha1_Pkg(in, out, s)
}

func autoConvert_v1alpha1_PkgList_To_packages_PkgList(in *PkgList, out *packages.PkgList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]packages.Pkg)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PkgList_To_packages_PkgList is an autogenerated conversion function.
func Convert_v1alpha1_PkgList_To_packages_PkgList(in *PkgList, out *packages.PkgList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PkgList_To_packages_PkgList(in, out, s)
}

func autoConvert_packages_PkgList_To_v1alpha1_PkgList(in *packages.PkgList, out *PkgList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Pkg)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_packages_PkgList_To_v1alpha1_PkgList is an autogenerated conversion function.
func Convert_packages_PkgList_To_v1alpha1_PkgList(in *packages.PkgList, out *PkgList, s conversion.Scope) error {
	return autoConvert_packages_PkgList_To_v1alpha1_PkgList(in, out, s)
}

func autoConvert_v1alpha1_PkgSpec_To_packages_PkgSpec(in *PkgSpec, out *packages.PkgSpec, s conversion.Scope) error {
	out.PublicName = in.PublicName
	out.Version = in.Version
	out.DisplayName = in.DisplayName
	out.Description = in.Description
	out.Template = (*kappctrlv1alpha1.App)(unsafe.Pointer(in.Template))
	return nil
}

// Convert_v1alpha1_PkgSpec_To_packages_PkgSpec is an autogenerated conversion function.
func Convert_v1alpha1_PkgSpec_To_packages_PkgSpec(in *PkgSpec, out *packages.PkgSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PkgSpec_To_packages_PkgSpec(in, out, s)
}

func autoConvert_packages_PkgSpec_To_v1alpha1_PkgSpec(in *packages.PkgSpec, out *PkgSpec, s conversion.Scope) error {
	out.PublicName = in.PublicName
	out.Version = in.Version
	out.DisplayName = in.DisplayName
	out.Description = in.Description
	out.Template = (*kappctrlv1alpha1.App)(unsafe.Pointer(in.Template))
	return nil
}

// Convert_packages_PkgSpec_To_v1alpha1_PkgSpec is an autogenerated conversion function.
func Convert_packages_PkgSpec_To_v1alpha1_PkgSpec(in *packages.PkgSpec, out *PkgSpec, s conversion.Scope) error {
	return autoConvert_packages_PkgSpec_To_v1alpha1_PkgSpec(in, out, s)
}

func autoConvert_v1alpha1_PkgStatus_To_packages_PkgStatus(in *PkgStatus, out *packages.PkgStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]kappctrlv1alpha1.AppCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_PkgStatus_To_packages_PkgStatus is an autogenerated conversion function.
func Convert_v1alpha1_PkgStatus_To_packages_PkgStatus(in *PkgStatus, out *packages.PkgStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_PkgStatus_To_packages_PkgStatus(in, out, s)
}

func autoConvert_packages_PkgStatus_To_v1alpha1_PkgStatus(in *packages.PkgStatus, out *PkgStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]kappctrlv1alpha1.AppCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_packages_PkgStatus_To_v1alpha1_PkgStatus is an autogenerated conversion function.
func Convert_packages_PkgStatus_To_v1alpha1_PkgStatus(in *packages.PkgStatus, out *PkgStatus, s conversion.Scope) error {
	return autoConvert_packages_PkgStatus_To_v1alpha1_PkgStatus(in, out, s)
}
